### ISSUE TITLE
Not able to parse official Microsoft XLSX/DOCX/PPTX files with LlamaParseReader

### ISSUE THREAD

**Issue by ianwoodfill** [run-llama/LlamaIndexTS#1006]
Referring to `packages/llamaindex/src/readers/LlamaParseReader.ts`. It uses the magic number of the file to detect the file type before sending it to LlamaParse cloud. Microsoft Office files (pptx, xlsx, docx) are technically `application/zip`, and not `application/vnd.openxmlformats-officedocument.wordprocessingml.document` as the `LlamaParseReader` class expects, and therefore throws an error.

```
File has type \"application/zip\" which does not match supported MIME Types. Supported formats include: .pdf, .602, .abw,...
```

**Comment by himself65** [comment]
could you please give a example file to test?

**Comment by ianwoodfill** [comment]
Yup, any xlsx file created through Microsoft Excel, like the one attached. You can see it with the `Magic-bytes.js` playground here: https://larskoelpin.github.io/magic-bytes/

<img width="1146" alt="CleanShot 2024-07-02 at 17 10 22@2x" src="https://github.com/run-llama/LlamaIndexTS/assets/9495579/8f7429a8-2f62-4154-a411-0829b0419698">


[test.xlsx](https://github.com/user-attachments/files/16074238/test.xlsx)
