### ISSUE TITLE
llms missing in `@llamaindex/core` exports via npm

### ISSUE THREAD

**Issue by parhammmm** [run-llama/LlamaIndexTS#1012]
The `llms` module is not published https://github.com/run-llama/LlamaIndexTS/tree/main/packages/core/src/llms

https://www.npmjs.com/package/@llamaindex/core?activeTab=code

**Comment by himself65** [comment]
nice catch, seems like github action didn't update correctly

**Comment by himself65** [comment]
Please check 0.4.12

**Comment by parhammmm** [comment]
@himself65 yep that sorted it! thanks 😎
