### ISSUE TITLE
RegEx for extracting tool use is probably bogus

### ISSUE THREAD

**Issue by dhuebner** [run-llama/LlamaIndexTS#1019]
RegEx pattern defined in `extractToolUse` function  [here](https://github.com/run-llama/LlamaIndexTS/blob/e8f8bea969a23e30c356c61616d0d53e0e392ade/packages/llamaindex/src/agent/react.ts#L100)  seem to be bogus to me. 

A backslash is missing before the `}`.

Is: `/\s*Thought: (.*?)\nAction: ([a-zA-Z0-9_]+).*?\.*Input: .*?(\{.*?})/s`
Should be: `/\s*Thought: (.*?)\nAction: ([a-zA-Z0-9_]+).*?\.*Input: .*?(\{.*?\})/s` 

Example input to test with:
```
Thought: I need to rephrase the input.
Action: my_db
Input: {
  \\query\\: "What is LLamaIndex?"
}
```

**Comment by dhuebner** [comment]
Same in `extractJsonStr(text)` function?

**Comment by ranjanmangla1** [comment]
hey @himself65 and @dhuebner , new to project, can I take this one?

**Comment by himself65** [comment]
yeah
