### ISSUE TITLE
Open AI embeddings are not part of the package

### ISSUE THREAD

**Issue by rajeshradhakrishnanmvk** [run-llama/LlamaIndexTS#1045]
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './embeddings' is not defined by "exports" in ..\node_modules\@llamaindex\core\package.json
node_modules\llamaindex\dist\cjs\embeddings\OpenAIEmbedding.js:19:21

**Comment by marcusschiesser** [comment]
Thanks for letting us know! Fixed in 0.5.5
