### ISSUE TITLE
Default context window is used rather max model context window

### ISSUE THREAD

**Issue by zigamall** [run-llama/LlamaIndexTS#105]
<details open>
<summary>Checklist</summary>

- [ ] `packages/core/src/llm/LLM.ts`
> • Check where the context window is being set for each model. If it's being set to the default context window size instead of the maximum context window size for the model, change this to use the maximum context window size for the model.

- [ ] `packages/core/src/PromptHelper.ts`
> • Investigate the getAvailableContextSize method. If it's not correctly calculating the available context size, modify this method to correctly calculate the available context size.

- [X] `packages/core/src/tests/contextWindowSizeTest.ts`
> • Write tests to ensure that the correct context window size is being used for each model. These tests should check that the context window size is not the default context window size unless the maximum context window size for the model is the same as the default context window size.

</details>

**Comment by EmanuelCampos** [comment]
Closing due inactivity and for cleaning

Feel free to open again if needed
