### ISSUE TITLE
Can we export `getTopKEmbeddings` again?

### ISSUE THREAD

**Issue by parhammmm** [run-llama/LlamaIndexTS#1054]
In the latest release `getTopKEmbeddings` is no longer exported and moved to `/internals` but we we're using it in our setup. 

My question is should I make a PR to export `getTopKEmbeddings` again and if so where would you want it to be placed

**Comment by himself65** [comment]
You could expose it. There are many undocumented APIs, and some APIs shouldn't be exported by propose, but people use `export *`. So, if you want to make it stable, **please write a test** to stabilize it.
