### ISSUE TITLE
Add DeepSeek LLMs API provider

### ISSUE THREAD

**Issue by erik-balfe** [run-llama/LlamaIndexTS#1059]
I would like to add an llm adapter DeepSeek models
Their API is openAI compatible and the models are very good at coding and jsons. 

If it is ok, i may make it on my own and submit a pr

**Comment by erik-balfe** [comment]
Great, I'm in, you may assign this to me!

**Comment by erik-balfe** [comment]
@marcusschiesser 
Could you help me with this? I'm not aware of how it is usually done in GitHub. 
Ive just created a branch with my changes for this feature and pushed it.
Here is my PR https://github.com/run-llama/LlamaIndexTS/pull/1071
1. How can i attach it here?
2. Why it is said "No Changeset found" while there is a changeset file in the commit?

**Comment by marcusschiesser** [comment]
@erik-balfe you'll need to call `pnpm changeset` in the root folder, I updated that in https://github.com/run-llama/LlamaIndexTS/pull/1073/files

**Comment by erik-balfe** [comment]
Thanks, for the help. I think now I've made it right
