### ISSUE TITLE
RAG agent with system prompt not working

### ISSUE THREAD

**Issue by ozgur142** [run-llama/LlamaIndexTS#1079]
When i try to use system promt with rag , the system promt replace retrieved data so i can't use the retriever anymore

**Comment by marcusschiesser** [comment]
@ozgur142 which chat engine are you using?

**Comment by ozgur142** [comment]
> @ozgur142 which chat engine are you using?

ContextChatEngine;

  return new ContextChatEngine({
    chatModel: Settings.llm,
    retriever,
    // disable as a custom system prompt disables the generated context
    systemPrompt: process.env.SYSTEM_PROMPT,
  });
  
  when i uncomment systemPrompt, it replace retrieved data. if i comment the systemprompt i have retrieved data without systemprompt but if i uncomment it like on the example; retrieved data override from systemprompt

**Comment by ozgur142** [comment]
> > @ozgur142 which chat engine are you using?
> 
> ContextChatEngine;
> 
> return new ContextChatEngine({ chatModel: Settings.llm, retriever, // disable as a custom system prompt disables the generated context systemPrompt: process.env.SYSTEM_PROMPT, });
> 
> when i uncomment systemPrompt, it replace retrieved data. if i comment the systemprompt i have retrieved data without systemprompt but if i uncomment it like on the example; retrieved data override from systemprompt

@marcusschiesser

**Comment by marcusschiesser** [comment]
fixed by https://github.com/run-llama/LlamaIndexTS/pull/1088

**Comment by ozgur142** [comment]
thank you, it is working really nice
