### ISSUE TITLE
SentenceSplitter no longer exported in version 0.5.9+

### ISSUE THREAD

**Issue by hildoer** [run-llama/LlamaIndexTS#1096]
My project previously used version 0.5.6. I bumped the version to 0.5.12 (which was the latest at the time), and then deleted node_modules and reinstalled with npm install. TypeScript then started telling me that 'llamaindex' package does not export a field named: SentenceSplitter

My code looks like this:

```TypeScript
import { SentenceSplitter } from 'llamaindex';
```

I reverted back to 0.5.6 and it was all fine. I tried 0.5.12 again, and blew away my node_modules and package-lock.json before the npm install just to be sure. Sure enough TypeScript failed to compile. I did some testing with different versions and found that the break occurs in version 0.5.9. 

I would do a pull request to suggest a fix, but release 0.5.9 seems massive.

**Comment by marcusschiesser** [comment]
@hildoer - it's now in the core package, please try:
```
import { SentenceSplitter } from "@llamaindex/core/node-parser";
```

**Comment by bborn** [comment]
Just a ping to suggest you update your docs on this import here: https://ts.llamaindex.ai/modules/node_parser#textsplitter

**Comment by marcusschiesser** [comment]
@bborn `import { SentenceSplitter } from "llamaindex"` should work again
