### ISSUE TITLE
Outdate/broken Sentence tokenizer?

### ISSUE THREAD

**Issue by parhammmm** [run-llama/LlamaIndexTS#1118]
Came across an issue earlier, that highlighted the way the tokenizer works. I'm referring to the try/catch here

https://github.com/run-llama/LlamaIndexTS/blob/6f4549bdeac83ce54c626b4444df3463a8041d5e/packages/core/src/node-parser/utils.ts#L36-L48

I noticed `natural` is being shimmed in but it's the older version which is buggy and making the try/catch necessary. The new Sentence Splitter works quite well and doesn't have the same issues that would cause the tokenizer to fail.

Using a deprecated tokenizer and hiding the errors from it is quite messy which isn't ideal. 

`natural` is CommonJS only and so that makes sense as why it's being shimmed in but could we update to the latest `natural` and do something like the following inside `splitBySentenceTokenizer` while we wait for https://github.com/NaturalNode/natural/pull/744? would that break something in the packaging in LLamaindexTS @himself65 ?

```ts
  const {
    default: { SentenceTokenizer },
  } = await import("natural");

```

We can still try catch on the function but at least make it not silent... `console.log` at the minimum?

**Comment by petergoldstein** [comment]
@himself65 Any thoughts on this?  Would there be support for a PR that addresses updating the `natural` version?

**Comment by himself65** [comment]
I used tsup to bundle the natural package, yeah let me do a upgrade later

**Comment by parhammmm** [comment]
@himself65 thanks!  🙏
