### ISSUE TITLE
Support for CodeSplitter

### ISSUE THREAD

**Issue by Riphal** [run-llama/LlamaIndexTS#1122]
`llamaindex` python lib supports `CodeSplitter` for some time now. Is there any plan to support `CodeSplitter` in this lib as well?

Reference: https://docs.llamaindex.ai/en/v0.10.19/api/llama_index.core.node_parser.CodeSplitter.html

**Comment by himself65** [comment]
What language do you want to have? JS/TS or python

**Comment by Riphal** [comment]
JS/TS
