### ISSUE TITLE
database insertion errors are not thrown

### ISSUE THREAD

**Issue by ryanleecode** [run-llama/LlamaIndexTS#1153]
When running ingestion pipeline, if there are any database insertion errors w/ PgVector, the error is not propgated up the stack.

```ts
const vectorStore = yield* Effect.sync(() =>
    new PGVectorStore({
      dimensions: 512,
      connectionString: DATABASE_URL,
    })
  )
 const pipeline = yield* Effect.sync(() =>
  new IngestionPipeline({
    transformations: [
      new OpenAIEmbedding({ dimensions: 512, model: 'text-embedding-3-small' }),
    ],
    vectorStore,
  })
)
yield* Effect.tryPromise(() => pipeline.run({ documents }))
```

**Comment by ryanleecode** [comment]
Its just logged to the console

https://github.com/run-llama/LlamaIndexTS/blob/11b385633495456cba4c63c926018a37d200b18c/packages/llamaindex/src/storage/vectorStore/PGVectorStore.ts#L226

**Comment by ryanleecode** [comment]
It should also upsert something like this...

```ts
  async add(embeddingResults: BaseNode<Metadata>[]): Promise<string[]> {
    if (embeddingResults.length == 0) {
      console.debug('Empty list sent to PGVectorStore::add')
      return []
    }

    const sql: string = `
      INSERT INTO ${this.schemaName}.${this.tableName}
        (id, external_id, collection, document, metadata, embeddings)
      VALUES ($1, $2, $3, $4, $5, $6)
      ON CONFLICT (id) DO UPDATE SET
        external_id = EXCLUDED.external_id,
        collection = EXCLUDED.collection,
        document = EXCLUDED.document,
        metadata = EXCLUDED.metadata,
        embeddings = EXCLUDED.embeddings
      RETURNING id
    `

    const db = await this.getDb()
    const data = this.getDataToInsert(embeddingResults)

    const ret: string[] = []
    for (const params of data) {
      const result = await db.query(sql, params)
      if (result.rows.length) {
        const id = result.rows[0].id as string
        ret.push(id)
      }
    }

    return ret
  }
  ```

**Comment by marcusschiesser** [comment]
How about one `add` call is seen as a transaction? If that fails, it throws an error and rollbacks to everything before the `add` call? 
If you like the idea, it would be great if you can help with a PR

**Comment by ryanleecode** [comment]
> How about one `add` call is seen as a transaction? If that fails, it throws an error and rollbacks to everything before the `add` call? If you like the idea, it would be great if you can help with a PR

https://github.com/run-llama/LlamaIndexTS/issues/1153

**Comment by ryanleecode** [comment]
I add the transaction but i dont think its strictly necessary since the INSERT call is one statement and if it fails they all fail
