### ISSUE TITLE
missing stripInternal in tsconfig

### ISSUE THREAD

**Issue by ryanleecode** [run-llama/LlamaIndexTS#1160]
We are using `@internal` modifiers but we don't have `stripInternal` in any of the tsconfigs, so this is actually leaking into the d.ts.

https://github.com/run-llama/LlamaIndexTS/blob/main/packages/llamaindex/src/Settings.ts#L40

**Comment by himself65** [comment]
yes but we are not actually taking this seriously for now. It's okay but evetuanlly I will enable it
