### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by TheFox** [run-llama/LlamaIndexTS#119]
### Details

Some of the links in the documentation https://ts.llamaindex.ai/ referencing not found. For example for class VectorStoreIndex.

<details open>
<summary>Checklist</summary>

- [X] `apps/docs/docs/modules/high_level/data_index.md` ✅ Commit [`4a8a603`](https://github.com/run-llama/LlamaIndexTS/commit/4a8a6032e0fd041f9e0a007ce9e61492af9e5443)
<blockquote>• Check if the link to the VectorStoreIndex class documentation is correct. If it is not, correct the link.
• If the documentation for the VectorStoreIndex class does not exist, create a new markdown file for it in the appropriate location and link it in the data_index.md file.</blockquote>
<details open>
<summary>Sandbox Execution Logs</summary>

<details open>
<summary><code>trunk init</code> 1/1 ✅</summary>

<pre>⡿ Downloading Trunk 1.15.0...
⡿ Downloading Trunk 1.15.0...
⢿ Downloading Trunk 1.15.0...
⣻ Downloading Trunk 1.15.0...
⣽ Downloading Trunk 1.15.0...
⣾ Downloading Trunk 1.15.0...
⣷ Downloading Trunk 1.15.0...
⣯ Downloading Trunk 1.15.0...
⣟ Downloading Trunk 1.15.0...
⡿ Downloading Trunk 1.15.0...
⢿ Downloading Trunk 1.15.0...
⣻ Downloading Trunk 1.15.0...
⣽ Downloading Trunk 1.15.0...
⣾ Downloading Trunk 1.15.0...
⣷ Downloading Trunk 1.15.0...
✔ Downloading Trunk 1.15.0... done
⡿ Verifying Trunk sha256...
✔ Verifying Trunk sha256... done
⡿ Unpacking Trunk...
✔ Unpacking Trunk... done

✔ 14 linters were enabled (.trunk/trunk.yaml)

  actionlint 1.6.25 (2 github-workflow files)
  checkov 2.4.9 (16 json, 12 yaml files)
  eslint 8.49.0 (7 javascript, 111 typescript files)
  git-diff-check (207 files)
  markdownlint 0.36.0 (32 markdown files) (created .markdownlint.yaml)
  osv-scanner 1.3.6 (1 lockfile file)
  oxipng 8.0.0 (2 png files)
  prettier 3.0.3 (3 css, 7 javascript, 16 json, 32 markdown, 111 typescript, 11 yaml files)
  shellcheck 0.9.0 (2 shell files) (created .shellcheckrc)
  shfmt 3.6.0 (2 shell files)
  svgo 3.0.2 (5 svg files) (created svgo.config.js)
  trivy 0.45.0 (1 lockfile, 11 yaml files)
  trufflehog 3.55.1 (208 files)
  yamllint 1.32.0 (11 yaml files) (created .yamllint.yaml)

Next Steps

 1. Read documentation
    Our documentation can be found at https://docs.trunk.io

 2. Get help and give feedback
    Join the Trunk community at https://slack.trunk.io
</pre>
</details>

</details>

</details>

**Comment by EmanuelCampos** [comment]
Closing due inactivity and for cleaning

Feel free to open again
