### ISSUE TITLE
Install error Couldn't find package "@llamaindex/openai@0.1.1" required by "llamaindex" on the "npm" registry.

### ISSUE THREAD

**Issue by blackge** [run-llama/LlamaIndexTS#1198]
Looks like [Release 0.5.27](https://github.com/run-llama/LlamaIndexTS/releases/tag/llamaindex%400.5.27) might be causing an install error.

I got this message when doing `yarn add llamaindex`:

error Couldn't find package "@llamaindex/openai@0.1.1" required by "llamaindex" on the "npm" registry.

**Comment by marcusschiesser** [comment]
@blackge oops, sorry for the trouble, the package was private. Fixed in https://github.com/run-llama/LlamaIndexTS/pull/1200 - please use the latest release 0.6 or 0.5.26 (@himself65 )
