### ISSUE TITLE
Have the ability to modify the default variable from `@xenova/transformers` ?

### ISSUE THREAD

**Issue by abcfy2** [run-llama/LlamaIndexTS#1227]
Sometimes I need to change the `HF_ENDPOINT` in `@xenova/transformers`. But I can't find a way to do so when I use in `llamaindex`.

I find `@xenova/transformers` have a api [`env`](https://huggingface.co/docs/transformers.js/api/env) Could modify the `remoteHost`, Would you please also expose this API and let me modify it ?

Thanks.

**Comment by marcusschiesser** [comment]
@abcfy2 why does `import { env } from '@xenova/transformers';` not work?

**Comment by abcfy2** [comment]
> @abcfy2 why does `import { env } from '@xenova/transformers';` not work?

This will not working as expect:

```ts
import { env } from "@xenova/transformers";
import { HuggingFaceEmbedding, Settings } from "llamaindex";

env.remoteHost = "https://hf-mirror.com/";
Settings.embedModel = new HuggingFaceEmbedding();
```

I guess the reason is `import` is asynchronous. So before `env.remoteHost = "https://hf-mirror.com/";`, `@xenova/transformers` may initialized by `llamaindex`. So modify `env` is no longer working.

**Comment by marcusschiesser** [comment]
does it work to import it later lazily?
```
export async function lazyLoadTransformers() {
    transformer = await import("@xenova/transformers");
    transformer.env.remoteHost = "https://hf-mirror.com/"
}
```

**Comment by abcfy2** [comment]
Yes. It's working. I modified this file: https://github.com/run-llama/LlamaIndexTS/blob/main/packages/llamaindex/src/internal/deps/transformers.ts#L5

And build locally then installed to my project. It's working.

**Comment by himself65** [comment]
> Yes. It's working. I modified this file:
> 
> [`main`/packages/llamaindex/src/internal/deps/transformers.ts#L5](https://github.com/run-llama/LlamaIndexTS/blob/main/packages/llamaindex/src/internal/deps/transformers.ts?rgh-link-date=2024-09-19T09%3A11%3A29Z#L5)
> 
> And build locally then installed to my project. It's working.
> 
> So I think we can export `env` api from `transformers.ts`, and let other codes could modify it. Or allow environment variables to modify `env`.

It's a tricky thing that `@xenova/transformers` doesn't have bad support on non-nodejs runtime so I had to make it async. Yeah I think we could move to env package and make empty export for non-nodejs environment

**Comment by himself65** [comment]
Now you can do by this way

```
Settings.callbackManager.on("load-transformers", event => {
  const { transformers } = event.detail
  transformers.env.xxx = false
});
```

**Comment by abcfy2** [comment]
> Now you can do by this way
> 
> ```ts
> Settings.callbackManager.on("load-transformers", event => {
>   const { transformers } = event.detail
>   transformers.env.xxx = false
> });
> ```

Great. Thank you.
