### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by LawrenceGB** [run-llama/LlamaIndexTS#1276]
Error occurred after installing the package and running node.

Error: Cannot find module  - /node_modules/llamaindex/dist/cjs/synthesizers/utils.js

Version: 0.6.11

**Comment by himself65** [comment]
Im guessing you are bumping the llamaindex version from old one, we moved synthesizers module into `@llamaindex/core/response-synthesizers`

**Comment by LawrenceGB** [comment]
Ah yes, my bad! Thanks
