### ISSUE TITLE
Index record id not setting in Pinecone

### ISSUE THREAD

**Issue by LawrenceGB** [run-llama/LlamaIndexTS#1278]
I have been trying to get this to work all day and not sure if it is me or a bug.

I am setting id_ in a new Document like so

`new Document({
        id_: `${fileId}-${index}`,
        text: page.text,
        metadata: { page: page.page }
    })`

When it gets pushed to Pinecone it is saving this id to the metadata but creating a random UUID as the record id instead.

![Screenshot 2024-09-30 at 23 40 26](https://github.com/user-attachments/assets/d7733654-a799-46b2-ade7-ce8be6ccbb10)

**Comment by himself65** [comment]
we have some intergration pars are outdated, feel free to fix it if you have time. im working on other things right now
