### ISSUE TITLE
Images returning zero bytes from LlamaParseReader

### ISSUE THREAD

**Issue by LawrenceGB** [run-llama/LlamaIndexTS#1283]
```
const reader = new LlamaParseReader(llamaParams);
const jsonObjs = await reader.loadJson(tempFilePath);
const imageDicts = await reader.getImages(jsonObjs, "images");

```

The imgs being saved into the folder "images" are all zero bytes, yet in LlamaCloud the history shows the image is correctly processed.

------------------------

![Screenshot 2024-10-01 at 15 43 25](https://github.com/user-attachments/assets/1fe6da3d-40c2-4c66-93dc-ff7a0966d1d5)

**Comment by himself65** [comment]
checking this right now

**Comment by himself65** [comment]
I cannot reproduce this, but I'm pretty sure you pass the wrong loadJson file path

You can enable log by this way

```ts
const reader = new LlamaParseReader({
  ignoreErrors: false
});
```
