### ISSUE TITLE
question extractor doesnt even use the prompt template

### ISSUE THREAD

**Issue by ryanleecode** [run-llama/LlamaIndexTS#1328]
question extractor doesnt use the user provided the prompt template

https://github.com/run-llama/LlamaIndexTS/blob/1ea40147466070c5428d530927f72af9ee204ee2/packages/llamaindex/src/extractors/MetadataExtractors.ts#L326

**Comment by bborn** [comment]
@himself65 tried my hand at a PR for this here: https://github.com/run-llama/LlamaIndexTS/pull/1335
