### ISSUE TITLE
Node 18 is supposed to be supported, but it does not install on node 18.

### ISSUE THREAD

**Issue by EduardoFromTheFuture** [run-llama/LlamaIndexTS#1360]
When using yarn:
```error @huggingface/gguf@0.1.12: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.20.4"```

when using npm: 
```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@huggingface/gguf@0.1.12',
npm warn EBADENGINE   required: { node: '>=20' },
npm warn EBADENGINE   current: { node: 'v18.20.4', npm: '10.7.0' }
npm warn EBADENGINE }
```

**Comment by himself65** [comment]
Related: https://github.com/huggingface/huggingface.js/pull/540

**Comment by himself65** [comment]
Nice catch, it's a dependency issue when intergrate with huggingface, We gonna drop 18 in the future of course, but today is a not a good time, let me check if any workaround

**Comment by himself65** [comment]
I think the workaround is to make it peer dependency

**Comment by PinkFromTheFuture** [comment]
Thanks. In that case, we're dropping another dependency that worked only on
node <= 18

**Comment by himself65** [comment]
Im gonna drop nodejs 18 recently because nodejs just set 22 as LTS

**Comment by PinkFromTheFuture** [comment]
Sounds fair
