### ISSUE TITLE
import process error 

### ISSUE THREAD

**Issue by ramprasadchauhan** [run-llama/LlamaIndexTS#1382]
I get error from nodemodules , node_modules/@llamaindex/openai/dist/index.js:6
import { getEnv, Tokenizers, process } from '@llamaindex/env';
                             ^^^^^^^
SyntaxError: The requested module '@llamaindex/env' does not provide an export named 'process'

when in given file we remove process , then it work fine. so please fix the bug , it process required or not . if required , then it should be export from @llamaindex/env. Thank you

**Comment by himself65** [comment]
have you bump the verion? I think it's exported for all js runtime/

**Comment by ramprasadchauhan** [comment]
currently it work fine , when we install version ^0.7.8 . here work fine. Thank you for fixing the bug
