### ISSUE TITLE
Cannot provide a defaultTool to Agent chat()

### ISSUE THREAD

**Issue by JeremyKirkham** [run-llama/LlamaIndexTS#1411]
**Describe the bug**
The python version of LlamaIndex allows you to force an agent to always use a tool (https://github.com/run-llama/llama_index/issues/13957) 
```
# Forced function call
response = agent.chat("What is 5 * 2?", tool_choice="useless_tool")
```

There appears to be no such way to do this with Typescript.

- OS: [e.g. macOS, Linux]
- JS Runtime / Framework / Bundler (select all applicable)
- [x] Node.js

**Comment by himself65** [comment]
we don't support that in LITS for now, PR are welcome

**Comment by himself65** [comment]
For now, you can pass `additionalChatOptions.tool_choice`
