### ISSUE TITLE
Sweep: Add support for Ollama

### ISSUE THREAD

**Issue by siquick** [run-llama/LlamaIndexTS#148]
### Details

Would be great to see support for Ollama in the same way that the Python version of Llama Index does.

Useful links:

https://github.com/jmorganca/ollama
https://gpt-index.readthedocs.io/en/v0.8.30/examples/llm/ollama.html

<details open>
<summary>Checklist</summary>

- [X] ``packages/core/src/llm/Ollama.ts`` ✅ Commit <a href='https://github.com/run-llama/LlamaIndexTS/commit/52d94d44587f5a97b19fa8f59a64a5c7fba4ffe7'><code>52d94d4</code></a>
- [X] `packages/core/src/llm/Ollama.ts` ❌ Sandbox failed so I made additional changes
- [X] `packages/core/src/llm/Ollama.ts` ❌ Sandbox failed so I made additional changes
- [X] `packages/core/src/llm/Ollama.ts` ❌ Sandbox failed so I made additional changes
- [X] `packages/core/src/llm/Ollama.ts` ❌ Sandbox failed so I made additional changes
- [X] `packages/core/src/llm/Ollama.ts` ❌ Sandbox failed so I made additional changes
- [X] ``packages/core/src/llm/LLM.ts`` ✅ Commit <a href='https://github.com/run-llama/LlamaIndexTS/commit/8675a140e55881a53b2fdb12528d1c5a9ea18af9'><code>8675a14</code></a>
- [X] `packages/core/src/llm/LLM.ts` ❌ Sandbox failed so I made additional changes
- [ ] `packages/core/src/tests/Ollama.test.ts`

![Flowchart](http://24.199.78.105:8082/public/19fa06923b185388643f0e2ea7490a86e1d9d083371264ba6c67dcf375d15583_148_flowchart.svg)
</details>

**Comment by EmanuelCampos** [comment]
LLM: https://ts.llamaindex.ai/modules/llms/available_llms/ollama
Embedding: https://ts.llamaindex.ai/modules/embeddings/available_embeddings/ollama
