### ISSUE TITLE
Add support for Anthropic's prompt caching feature (beta)

### ISSUE THREAD

**Issue by erik-balfe** [run-llama/LlamaIndexTS#1487]
Currently using Claude through LlamaIndex. Want to implement Anthropic's prompt caching to reduce costs and latency.

Key points:
- Needs support for `anthropic-beta: prompt-caching-2024-07-31` header (feature in beta)
- Cache control parameter in message blocks
- Usage tracking fields in response (probably is returned right now as API returns it)

Despite beta status, can save up to 90% on input tokens for cached content. Critical for cost optimization in almost any agent scenario due to:
- Long conversations with growing history
- Repeated big system messages
- Tool definitions

Links:
- Anthropic docs: https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

**Comment by himself65** [comment]
We support that now! Here is the example

```ts
import { Anthropic } from "llamaindex";

const anthropic = new Anthropic({
  model: "claude-3-5-sonnet-20241022",
});

const entireBook = await fetch(
  "https://www.gutenberg.org/files/1342/1342-0.txt",
).then((response) => response.text());

const response = await anthropic.chat({
  messages: [
    {
      content:
        "You are an AI assistant tasked with analyzing literary works. Your goal is to provide insightful commentary on themes, characters, and writing style.\n",
      role: "system",
    },
    {
      content: entireBook,
      role: "system",
      options: {
        cache_control: {
          type: "ephemeral",
        },
      },
    },
    {
      content: "analyze the major themes in Pride and Prejudice.",
      role: "user",
    },
  ],
});

console.log(response.message.content);
```
