### ISSUE TITLE
Trying to create a VectorStoreIndex from an already created VectorStore

### ISSUE THREAD

**Issue by DavideCarvalho** [run-llama/LlamaIndexTS#150]
### Details

I'm trying to create a VectorStoreIndex from a vector_store.json file

I'm able to create the SimpleVectorStore, but when I try to use VectorStoreIndex.fromVectorStore, I receive an error

![image](https://github.com/run-llama/LlamaIndexTS/assets/15630886/742bd430-901e-4820-9c89-6111881c153e)

![image](https://github.com/run-llama/LlamaIndexTS/assets/15630886/523d259f-42a4-4322-9bf3-655553ae8f69)

if I use "fromPersistPath", the error changes

![image](https://github.com/run-llama/LlamaIndexTS/assets/15630886/bb1f0513-30cc-4949-93c1-99f0524c69e5)

![image](https://github.com/run-llama/LlamaIndexTS/assets/15630886/5250d2a9-572e-4422-b7e4-ea72ccfaee8a)

<details open>
<summary>Checklist</summary>

- [X] ``packages/core/src/indices/vectorStore/VectorStoreIndex.ts`` ✅ Commit <a href='https://github.com/run-llama/LlamaIndexTS/commit/32a482dcacede8ba8cdf991a6ec9dee9becb88b4'><code>32a482d</code></a>
- [X] `packages/core/src/indices/vectorStore/VectorStoreIndex.ts` ❌ Sandbox failed so I made additional changes
- [X] `packages/core/src/indices/vectorStore/VectorStoreIndex.ts` ❌ Sandbox failed so I made additional changes
- [X] `packages/core/src/indices/vectorStore/VectorStoreIndex.ts` ❌ Sandbox failed so I made additional changes
- [X] `packages/core/src/indices/vectorStore/VectorStoreIndex.ts` ✅ Sandbox ran successfully
- [X] `packages/core/src/indices/vectorStore/VectorStoreIndex.ts` ✅ Sandbox ran successfully
- [X] `packages/core/src/indices/vectorStore/VectorStoreIndex.ts` ✅ Sandbox ran successfully
- [ ] `apps/docs/docs/starter.md`
- [ ] `apps/docs/docs/modules/low_level/storage.md`
- [X] ``packages/core/src/storage/vectorStore/types.ts`` ✅ Commit <a href='https://github.com/run-llama/LlamaIndexTS/commit/328e8c6b6eb245f1fa604bddf0e06f3299a2e831'><code>328e8c6</code></a>
- [X] `packages/core/src/storage/vectorStore/types.ts` ❌ Sandbox failed so I made additional changes
- [X] ``packages/core/src/storage/vectorStore/SimpleVectorStore.ts`` ✅ Commit <a href='https://github.com/run-llama/LlamaIndexTS/commit/b8e6441209aba0ce9a0842caad19f700b4019642'><code>b8e6441</code></a>
- [X] `packages/core/src/storage/vectorStore/SimpleVectorStore.ts` ❌ Sandbox failed so I made additional changes
- [X] `packages/core/src/storage/vectorStore/SimpleVectorStore.ts` ✅ Sandbox ran successfully

![Flowchart](http://24.199.78.105:8082/public/83862fd97c21dea010ee733661defac79252e8d51e753a48135b316b8ab2dd3a_150_flowchart.svg)
</details>

**Comment by DavideCarvalho** [comment]
The idea is to try to create the index from an already created vector store - maybe uploaded on S3.

I don't know if that's possible

**Comment by EmanuelCampos** [comment]
From some last tests looks to be working now, ensure to be on the latest version and feel free to open the issue again if needed
