### ISSUE TITLE
retriever error with Pinecone vector store

### ISSUE THREAD

**Issue by LawrenceGB** [run-llama/LlamaIndexTS#1510]
**Describe the bug**
When fetching retriever from Pinecone with OpenAi embeddings it throws an error.

**To Reproduce**
Code to reproduce the behavior:

```ts
 const serviceContext = serviceContextFromDefaults({
        chunkSize: 8191,
        chunkOverlap: 0,
    });

    const pcvs = new PineconeVectorStore({
        indexName: 'user-index',
        namespace: user.uid
    });

    const index = await VectorStoreIndex.fromVectorStore(pcvs, serviceContext);

    const retriever = index.asRetriever({
        similarityTopK: 3
    });

    const results = await retriever.retrieve(
        {
            query: "When are you open?",
        }
    );
```

**Expected behavior**
It should return the correct answer but instead as the error-

```
 External network resource requested!
   - URL: "https://api.openai.com/v1/embeddings"
You must enter a `filter` object with at least one key-value pair.

```

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- JS Runtime / Framework / Bundler (select all applicable)
- [X ] Node.js
- [ ] Deno
- [ ] Bun
- [ ] Next.js
- [ ] ESBuild
- [ ] Rollup
- [ ] Webpack
- [ ] Turbopack
- [ ] Vite
- [ ] Waku
- [ ] Edge Runtime
- [ ] AWS Lambda
- [ ] Cloudflare Worker
- [ ] Others (please elaborate on this)
- Version 0.8.17

**Additional context**

**Comment by himself65** [comment]
Similar error here

https://github.com/langchain-ai/langchainjs/issues/6926

I'm guessing pinecone has some breaking changes

**Comment by himself65** [comment]
Thanks for reporting, we do have some lack of maintaince of vector stores, but I will add e2e tet for each one to make sure it won't break the simple cases
