### ISSUE TITLE
Env issues with Cloudflare Worker and Hono

### ISSUE THREAD

**Issue by LawrenceGB** [run-llama/LlamaIndexTS#1515]
**Describe the bug**
I am having trouble getting the env to register for a cloudlfare worker using Hono framework.
I have tried using setEnvs from @llamaindex/env but did not work, and I am even passing the apiKeys but still throwing an error.

**To Reproduce**
Code to reproduce the behavior: I just write this test endpoint. 

```ts
app.post('/llm', async (c) => {

	// Testing endpoint

	if (c.req.method !== 'POST') {
		return c.text('Method not allowed', 405);
	}

	const {message} = await c.req.json();

	const {
		QueryEngineTool,
		serviceContextFromDefaults,
		VectorStoreIndex,
		OpenAIAgent,
		Settings,
		OpenAI,
		OpenAIEmbedding,
	} = await import("@llamaindex/edge");

	const {
		PineconeVectorStore
	} = await import("@llamaindex/edge/storage/vectorStore/PineconeVectorStore");

	const llm = new OpenAI({
		model: "gpt-4o-mini",
		apiKey: c.env.OPENAI_API_KEY
	});

	Settings.embedModel = new OpenAIEmbedding({
		model: "text-embedding-3-small",
		apiKey: c.env.OPENAI_API_KEY
	});

	const serviceContext = serviceContextFromDefaults({
		llm,
		chunkSize: 8191,
		chunkOverlap: 0,
	});

	const store = new PineconeVectorStore({
		namespace: '8xolsn4ulEQGdhnhP76yCzfLHdOZ'
	});

	const index = await VectorStoreIndex.fromVectorStore(store, serviceContext);

	const retriever = await index.asRetriever({
		similarityTopK: 3
	});

	// Create a query engine
	const queryEngine = await index.asQueryEngine({
		retriever,
	});

	const tools = [
		new QueryEngineTool({
			queryEngine: queryEngine,
			metadata: {
				name: "business_info_tool",
				description: "This tool can answer questions based " +
					"on business information. Return not found if you" +
					" can't find the answer in the documents.",
			},
		}),
	];


	// Initialize the agent
	const agent = new OpenAIAgent({ tools });

	// Query the agent
	let response = await agent.chat({
		message: message
	});

	return new Response(response.message.content);

})

```

**Expected behavior**
It is crashing with the following error
` 
Error: Set OpenAI Key in OPENAI_API_KEY env variable
`

**Screenshots**

**Desktop (please complete the following information):**

- OS: macOS
- JS Runtime / Framework / Bundler (select all applicable)
- [ ] Node.js
- [ ] Deno
- [ ] Bun
- [ ] Next.js
- [ ] ESBuild
- [ ] Rollup
- [ ] Webpack
- [ ] Turbopack
- [ ] Vite
- [ ] Waku
- [X ] Edge Runtime
- [ ] AWS Lambda
- [X ] Cloudflare Worker
- [ ] Others (please elaborate on this)
- Version 0.3.8

**Additional context**

**Comment by himself65** [comment]
first, `@llamaindex/edge` is already deprecated

**Comment by himself65** [comment]
im gonna add example for your case

**Comment by LawrenceGB** [comment]
Ah right, I must of been reading the old example, that would be great, thanks mate!

**Comment by himself65** [comment]
cloudflare increase the upload file size from 1mb to 3mb, so our example is working for free tier
