### ISSUE TITLE
Cannot find module '@llamaindex/readers/obsidian' from '****/node_modules/llamaindex/dist/readers/index.js'`

### ISSUE THREAD

**Issue by charnould** [run-llama/LlamaIndexTS#1534]
**Describe the bug**
I've been using LlamaIndex to chunk some markdown files and it was working like a charm. Thanks for the lib. However I've just upgraded to 0.8.24 and the very same code does not work any more.

`Cannot find module '@llamaindex/readers/obsidian' from '/Users/charnould/GitHub/pierre/node_modules/llamaindex/dist/readers/index.js'`

I've tried to delete node_modules and reinstall, to downgrade... and still this error.

This only part in my code where I use Llamaindex uses:  
`import { Document, MarkdownNodeParser } from 'llamaindex'
`

Any idea? Thanks.

**To Reproduce**
See screenshot, `readers/obsidian` does not exist.

**Expected behavior**
It should work.

**Screenshots**

![Capture d’écran 2024-11-30 à 17 04 47](https://github.com/user-attachments/assets/c5d6e21b-06e7-4dec-98b3-604e61ce3a1d)

**Desktop (please complete the following information):**

- OS: macOS
- JS Runtime : Bun (1.1.38)

**Additional context**
None

**Comment by jzhao62** [comment]
i will double check on this

**Comment by charnould** [comment]
> i will double check on this

If I delete `import` (line 14) it works again.

**Comment by jzhao62** [comment]
it seems like the 
`node_modules/@llamaindex/readers/package.json` version 1.0.17
is not the latest one in the main branch

<img width="1037" alt="Screen Shot 2024-12-01 at 00 50 05" src="https://github.com/user-attachments/assets/9aa71a60-3269-41be-a69d-cacca9cfc5ba">

**Comment by himself65** [comment]
we should update changelog and release a new version for that
