### ISSUE TITLE
OpenAIAgent chat with stream option works incorrectly

### ISSUE THREAD

**Issue by tintotechbee** [run-llama/LlamaIndexTS#1538]
Hi guys. I have faced with the problem in using OpenAIAgent.chat with stream option. I follow those steps in: https://stackblitz.com/github/run-llama/LlamaIndexTS/tree/main/examples?file=agent%2Fstream_openai_agent.ts to create an agent which will use tools for answering the question from users.
```typescript

  const agent = new OpenAIAgent({
    tools: [functionTool, functionTool2],
  });

  const stream = await agent.chat({
    message: "Divide 16 by 2 then add 20",
    stream: true,
  });

  console.log("Response:");

  for await (const { delta } of stream) {
    process.stdout.write(delta);
  }
``` 
With stream option, I expected that the response would be chunk data and each chunk should have the different created value.
But I console.log each chunk and I found out: all chunk have the same created value and they seem be created and returned at the same time because I had to wait for a long time to get the object result from **OpenAIAgent.chat()**. It is slower than when I was using **ChatEngine.chat()**.

These are my result, they are pretty much so i captured some of them:
![image](https://github.com/user-attachments/assets/2306bc97-ee85-4fbe-9688-581d0e35804e)
![image](https://github.com/user-attachments/assets/8ca04a02-92be-43d6-a3fe-cb63f6f34e7a)
![image](https://github.com/user-attachments/assets/971a2d00-b686-4ab0-be7f-d64508b29db6)

I am running my project on:
- [21.4.0] Node.js
- [0.8.22] LlamaIndex

**Comment by jzhao62** [comment]
i think the timestamp you highlighted refers to the time the initial request got dispatched.

**Comment by himself65** [comment]
yes, this should be the expected result, openai just returns that. If you want to timestramp, you can use `Date.now` or something at the right time.

For the performance issue, could you give me the comperation of agent and chat engine? I will check that

**Comment by tintotechbee** [comment]
@himself65 Thank you for replying. I got the timestamp information. But i am still confused about the performance between OpenAIAgent Chat and Chat Engine. I will show my code to compare the performance between them:

### The first, I will test the Open AI Agent Chat following the example from LlamaIndex (https://stackblitz.com/github/run-llama/LlamaIndexTS/tree/main/examples?file=agent%2Fstream_openai_agent.ts)
My code:
```typescript
      const agent = new OpenAIAgent({
        tools: [functionTool, functionTool2],
      });

      const startToCreateStreamAt = new Date().getTime();
      console.log("Start to create stream result: ", startToCreateStreamAt);
    
      const stream = await agent.chat({
        message: "Divide 16 by 2 then add 20",
        stream: true,
      });

      console.log(`Stream result: `, stream)
      const finishToCreateStream = new Date().getTime();
      console.log("Finish to create stream result: ", finishToCreateStream);
      console.log(`We spend ${(finishToCreateStream-startToCreateStreamAt)/1000} seconds`)
      
    
      const startToStreamResponse = new Date().getTime();
      console.log("Start to stream response: ", startToStreamResponse);
      console.log("Response: ")
      
      for await (const { delta } of stream) {
        process.stdout.write(delta);
      }

      const finishToStreamResponse = new Date().getTime();
      console.log("\nFinish to stream response: ", finishToStreamResponse);
      console.log(`We spend ${(finishToStreamResponse-startToStreamResponse)/1000} seconds`)

     console.log(`Totally, we spend ${(finishToStreamResponse-startToCreateStreamAt)/1000} for the entire progress`)
``` 
Result:
```shell
Start to create stream result:  1733194353938
Stream result:  ReadableStream { locked: false, state: 'readable', supportsBYOB: false }
Finish to create stream result:  1733194357355
We spend 3.417 seconds
Start to stream response:  1733194357355
Response:
The result of dividing 16 by 2 is 8, and when you add 20 to that, the final result is 28.
Finish to stream response:  1733194357361
We spend 0.006 seconds
Totally, we spend 3.423 for the entire progress
``` 

Explaination: I simply run again the code from the example and provide some lines to console the time.

### The second, i will run chat engine to ask the same question
My code:
```typescript
      const chatEngine = new SimpleChatEngine();

      const startToCreateStreamAt = new Date().getTime();
      console.log("Start to create stream result: ", startToCreateStreamAt);

      const stream = await chatEngine.chat({
        message:"Divide 16 by 2 then add 20",
        stream:true
      })
      console.log(`Stream result: `, stream)
      const finishToCreateStream = new Date().getTime();
      console.log("Finish to create stream result: ", finishToCreateStream);
      console.log(`We spend ${(finishToCreateStream-startToCreateStreamAt)/1000} seconds`)

      const startToStreamResponse = new Date().getTime();
      console.log("Start to stream response: ", startToStreamResponse);
      console.log("Response: ")
      for await (const { delta } of stream) {
        process.stdout.write(delta);
      }
      const finishToStreamResponse = new Date().getTime();
      console.log("\nFinish to stream response: ", finishToStreamResponse);
      console.log(`We spend ${(finishToStreamResponse-startToStreamResponse)/1000} seconds`)

      console.log(`Totally, we spend ${(finishToStreamResponse-startToCreateStreamAt)/1000} for the entire progress`)
``` 
Result:
```shell
Start to create stream result:  1733194357363
Stream result:  Object [AsyncGenerator] {}
Finish to create stream result:  1733194357370
We spend 0.007 seconds
Start to stream response:  1733194357370
Response:
First, divide 16 by 2:

\[ 16 \div 2 = 8 \]

Then, add 20:

\[ 8 + 20 = 28 \]

So, the final result is 28.
Finish to stream response:  1733194358275
We spend 0.905 seconds
Totally, we spend 0.912 for the entire progress
``` 

So you can see, with the simple question:
- OpenAIAgent chat will spend 3.417 seconds before starting to stream data to show each junk. And the progress to stream all data just costs 0.006 seconds.
- ChatEngine will spend 0.007 seconds before starting to stream data to show each junk and it costs 0.905 for this progress

What i expected:
- I expected that when i used the OpenAIAgent Chat, i would get the first junk to show as soos as ChatEngine. But i had to wait for a long time to get the first chunk (3.417s for the simple question)
- I think the OpenAIAgent's process waits for all junks from OpenAI and send them all at the same time instead of sending junk by junk.

Sorry if i say something wrong, i completely new at this field and is trying to study.
