### ISSUE TITLE
Sweep: Request the SimpleMongoReader

### ISSUE THREAD

**Issue by dinhan92** [run-llama/LlamaIndexTS#156]
### Details

In llama index python, I see that there is SimpleMongoReader. In the nodejs version, I don't see that in documentation. Can you add it? Or is there other way to use Mongo data?

<details open>
<summary>Checklist</summary>

- [X] Modify `packages/core/src/readers/SimpleMongoReader.ts` ! No changes made
- [X] Create `packages/core/src/tests/SimpleMongoReader.test.ts` ✓ https://github.com/run-llama/LlamaIndexTS/commit/94961e8f908e4b89b04f00fcba7f03849e6a08f9
- [X] Check `packages/core/src/tests/SimpleMongoReader.test.ts` ✗
- [X] Modify `packages/core/tsconfig.json` ✓ https://github.com/run-llama/LlamaIndexTS/commit/59169d6c8bfa068d820fc9b2f864c112e308a09c
- [X] Check `packages/core/tsconfig.json` ✗
- [X] Modify `.eslintrc.json` ! No changes made
- [X] Check `packages/core/tsconfig.json` ✗
- [X] Check `packages/core/src/tests/SimpleMongoReader.test.ts` ✗

![Flowchart](http://24.199.78.105:8082/public/1cad765f1a9e139703045227421647a4db37c4ba5a92edca37ba065e5520ef1f_156_flowchart.svg)
</details>

**Comment by dinhan92** [comment]
When coding, I still do not see the SimpleMongoReader like in Python. How to use it?

**Comment by marcusschiesser** [comment]
@dinhan92 I just finished a PR that exports the SimpleMongoReader. Feel free to test it: https://github.com/run-llama/LlamaIndexTS/pull/204/files

**Comment by dinhan92** [comment]
@marcusschiesser was this merged to main branch ? I installed using npm

**Comment by EmanuelCampos** [comment]
It was merged

closing due to inactvity and cleaning the repo
