### ISSUE TITLE
Sweep: [create-lamma] REPLICATE_API_TOKEN required? 

### ISSUE THREAD

**Issue by hemanth** [run-llama/LlamaIndexTS#183]
### Details

I created a new app with `npx create-llama` edited `route.ts` to use the below:

```js
    const llm = new LlamaDeuce({
      model: "Llama-2-70b-chat-4bit",
    });
```

But seeing the error: 

```js
[LlamaIndex] Error: Set Replicate token in REPLICATE_API_TOKEN env variable
    at new ReplicateSession (/private/tmp/specsplain/node_modules/llamaindex/dist/index.js:1478:13)
    at new LlamaDeuce (/private/tmp/specsplain/node_modules/llamaindex/dist/index.js:1733:97)
    at POST (webpack-internal:///(rsc)/./app/api/chat/route.ts:32:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /private/tmp/specsplain/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:62499
```

`REPLICATE_API_TOKEN` is a must to load `llama`? The doc doesn't mention it.

<details open>
<summary>Checklist</summary>

- [X] Modify `packages/create-llama/templates/types/simple/nextjs/app/api/chat/route.ts` ✓ https://github.com/run-llama/LlamaIndexTS/commit/7a9ca3db8e06a491f72742d38c0e4877745f8433
- [X] Modify `packages/create-llama/README.md` ✓ https://github.com/run-llama/LlamaIndexTS/commit/41ed3012db243e7c4e10456aba7123c91b63e4b4

![Flowchart](http://24.199.78.105:8082/public/22cb35b5b5ce71d096403e76539c6f99d8757b04ba4174c9a70bc19f25b9538a_183_flowchart.svg)
</details>

**Comment by yisding** [comment]
Yes, currently Llama2 requires Replicate. We don't have any support for local Llama2 yet, although it's something I want to add at some point.

**Comment by hemanth** [comment]
@yisding Ah okies. Ollama++
