### ISSUE TITLE
[create-lamma] Support Google's PaLM API

### ISSUE THREAD

**Issue by hemanth** [run-llama/LlamaIndexTS#192]
### Details

PaLM API would be a good addon?

P.S: Would be happy to contribute.

**Comment by himself65** [comment]
I'd like to help on this

**Comment by petergoldstein** [comment]
Is this still desired now that Gemini support is in?  The PaLM API is deprecated as I understand it - https://ai.google.dev/palm_docs/deprecation

**Comment by marcusschiesser** [comment]
@petergoldstein Yes it seems like we don't want that in the main package at least. @hemanth feel free to reopen the ticket if needed
