### ISSUE TITLE
Sweep: [create-lamma] allow model selection on CLI

### ISSUE THREAD

**Issue by hemanth** [run-llama/LlamaIndexTS#193]
### Details

```sh
❯ npx create-llama
Need to install the following packages:
  create-llama@0.0.5
Ok to proceed? (y) y
✔ What is your project named? … foo
✔ Which template would you like to use? › Chat with streaming
✔ Which framework would you like to use? › NextJS
✔ Which UI would you like to use? › Shadcn
✔ Which chat engine would you like to use? › SimpleChatEngine
✔ **Please provide your llm of choice (leave blank to skip): …** 
✔ Please provide your API key (leave blank to skip): … 
✔ Would you like to use ESLint? … No / Yes
```

P.S: Would be happy to contribute.

<details open>
<summary>Checklist</summary>

- [X] Modify `packages/create-llama/create-app.ts` ✓ https://github.com/run-llama/LlamaIndexTS/commit/6c2fc21496d470a48cbf17a0117f3002315049a5
- [X] Check `packages/create-llama/create-app.ts` ✗
- [X] Modify `packages/create-llama/package.json` ! No changes made
- [X] Check `packages/create-llama/create-app.ts` ✗
- [X] Modify `packages/create-llama/index.ts` ✓ https://github.com/run-llama/LlamaIndexTS/commit/962126b77f0272ca45f1d3bd09900ae2e607c121
- [X] Check `packages/create-llama/index.ts` ✗
- [X] Modify `packages/create-llama/package.json` ✓ https://github.com/run-llama/LlamaIndexTS/commit/f8eecbe6d0c0528a6f13ecdf7041c703b2e82942
- [X] Check `packages/create-llama/package.json` ✗
- [X] Modify `packages/create-llama/package.json` ✓ https://github.com/run-llama/LlamaIndexTS/commit/af12adba2299560e86f7fc39a701d95fec2419a7
- [X] Check `packages/create-llama/package.json` ✗
- [X] Check `packages/create-llama/package.json` ✗
- [X] Check `packages/create-llama/index.ts` ✗
- [X] Modify `packages/create-llama/README.md` ✓ https://github.com/run-llama/LlamaIndexTS/commit/e6a0c548e84e8b81bb317f6ac1c7f71c2b246ce9
- [X] Check `packages/create-llama/README.md` ✗
- [X] Modify `packages/create-llama/package.json` ✓ https://github.com/run-llama/LlamaIndexTS/commit/02c34ba96f29623acdf1db715174403553ef40d6
- [X] Check `packages/create-llama/README.md` ✗
- [X] Modify `packages/create-llama/package.json` ! No changes made
- [X] Check `packages/create-llama/README.md` ✗
- [X] Modify `packages/create-llama/CHANGELOG.md` ✓ https://github.com/run-llama/LlamaIndexTS/commit/0266c3da9a94f6dc78eba8bf9dd72728df516cd6

![Flowchart](http://24.199.78.105:8082/public/7a3b1cfaa655397ddcd2a7547027c7b16cfe0c60bab5ae5e40d3fe6192af1be4_193_flowchart.svg)
</details>

**Comment by marcusschiesser** [comment]
already implemented

**Comment by hemanth** [comment]
@marcusschiesser which version? any changelog? thank you!

**Comment by marcusschiesser** [comment]
That was already some time ago: Version 0.0.11, see https://github.com/run-llama/LlamaIndexTS/blob/main/packages/create-llama/CHANGELOG.md#0011
