### ISSUE TITLE
[create-llama] Backend readme doesn't mention need to export env file before running

### ISSUE THREAD

**Issue by dantheman0207** [run-llama/LlamaIndexTS#198]
https://github.com/run-llama/LlamaIndexTS/blob/b64716d3f7e41e0b8db7421b7150cafd13026843/packages/create-llama/templates/types/simple/fastapi/README-template.md?plain=1#L15

I had provided my OpenAI API key during setup, and followed the instructions in the README exactly. However it still failed as it doesn't automatically load the `.env` file using dot-env or any other package. If that's the case the instructions should tell you to export this file before running, otherwise someone who follows the instructions exactly will have their first experience be triggering an error and having to debug it despite following the golden path.

**Comment by dantheman0207** [comment]
Fixed by this PR which unfortunately doesn't seem to automatically be linked: https://github.com/run-llama/LlamaIndexTS/pull/199

**Comment by logan-markewich** [comment]
Should be fixed in https://github.com/run-llama/LlamaIndexTS/pull/216
