### ISSUE TITLE
DX: `npm run generate` does not look at `.env.local`

### ISSUE THREAD

**Issue by seldo** [run-llama/LlamaIndexTS#226]
In the next.js backend, `npm run generate` expects `OPENAI_API_KEY` to be an environment variable.

The app generator creates a `.env.local` which the next.js app itself respects, so the generator should know to look in the same place.

**Comment by emapeire** [comment]
Hey @seldo, I posted this issue before #225. Maybe you should comment the problem there!

**Comment by marcusschiesser** [comment]
The issue is fixed in the latest version. NextJS is now using `.env` too.
