### ISSUE TITLE
Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by BoyYangzai** [run-llama/LlamaIndexTS#230]
When start a web applicataion with
```ts
import { Document } from "llamaindex";

const document = new Document({ text: 'Test' });

```

![image](https://github.com/run-llama/LlamaIndexTS/assets/94534613/00483eeb-0267-432b-b836-9129069de846)

It maybe same
- fix https://github.com/run-llama/LlamaIndexTS/pull/229

**Comment by marcusschiesser** [comment]
@BoyYangzai, yes, great catch. It's the AssemblyAIReader; we temporarily removed it in the latest llamaindex@0.0.37 version and added a new PR to handle the issue separately - see https://github.com/run-llama/LlamaIndexTS/pull/229 

The error message shouldn't happen any more, so closing this ticket.
