### ISSUE TITLE
modify system prompt of contextchatengine

### ISSUE THREAD

**Issue by alexfilothodoros** [run-llama/LlamaIndexTS#232]
That's an awesome project!
I have noticed that I can ask questions irrelevant to the documentation ingested.
Is there an option of adding a prompt that will restict this?
I'd be happy to help with that.

Cheers

**Comment by minnahu23** [comment]
great question, I have the same question, looking forward to suggestions! 

I am running the chat sample, how do you pass in system prompt for openapi,  I am new to nodejs, thank you!

    const document = new Document({ text: knowledge });
    const serviceContext = serviceContextFromDefaults({ chunkSize: 512 });
    const index = await VectorStoreIndex.fromDocuments([document], {
      serviceContext,
    });
    const retriever = index.asRetriever();
    retriever.similarityTopK = 5;
    const chatEngine = new ContextChatEngine({ retriever });
    const rl = readline.createInterface({ input, output });
  
    while (true) {
      const query = await rl.question("Query: ");
      const response = await chatEngine.chat(query);
      console.log(response.toString());
    }

**Comment by alexfilothodoros** [comment]
I haven't worked on that, but I am thinking of something like that:
For sure, this will not work all the time, but hopefully it can help you in thinking of something better.

```
var query = "What did the author do in college?";
  var prompt = "Use information only from the text"
  query = query  + "\n" + prompt;

  const response = await queryEngine.query(query);
```

**Comment by enricopolanski** [comment]
Any update on this?

This is kinda critical.

**Comment by marcusschiesser** [comment]
You can modify the system prompt used in the `ContextChatEngine` like this:
```
  const contextSystemPrompt = ({ context = "" }) => {
    return `Context information is below.
---------------------
${context}
---------------------`;
  };
  const chatEngine = new ContextChatEngine({
    retriever,
    contextSystemPrompt,
  });
```
Hope that helps

**Comment by rawwerks** [comment]
@marcusschiesser - would this same approach apply to `index.asQueryEngine()` ? 

(re: https://github.com/run-llama/LlamaIndexTS/issues/606)

**Comment by marcusschiesser** [comment]
Unfortunately not, we're working on it in #606
