### ISSUE TITLE
[NTH] How to Implement User-Provided OpenAI API Key Feature

### ISSUE THREAD

**Issue by emapeire** [run-llama/LlamaIndexTS#235]
We are exploring the possibility of allowing users to input their own OpenAI API keys in our application. This feature would greatly enhance user experience and scalability. However, it poses several challenges:

- **Security:** How can we securely handle and store user-provided API keys?
- **User Interface:** What is the best approach to allow users to input their API keys?
- **Backend Changes:** How should our backend be adapted to use different API keys for each user session?
- **Compliance:** Are there any legal or compliance issues with using user-provided OpenAI API keys?

I would appreciate your insights or suggestions on how we can effectively implement this feature.

**Comment by EmanuelCampos** [comment]
This is not related to llamaindex package

A suggestion would be to create the API Keys on your backend and store it in a secure way

And just pass as a parameter to `OpenAI` class
