### ISSUE TITLE
Next.js example without `appDir`?

### ISSUE THREAD

**Issue by johndo31** [run-llama/LlamaIndexTS#294]
Hi, is there any Next.js implementation with the old architecture? I just like it better. Thanks, John

**Comment by mehmetkursataydin** [comment]
I guess if you select without streaming when installing, it uses old Next.js router

**Comment by himself65** [comment]
We don't have such a template for now. But it's the same, just keep `api/***` and make your UI in old pages directory

 https://github.com/run-llama/LlamaIndexTS/tree/main/packages/create-llama/templates/types/streaming/nextjs/app

**Comment by marcusschiesser** [comment]
closing as not planned for now
