### ISSUE TITLE
Bug: Incorrect link takes to Page Not Found

### ISSUE THREAD

**Issue by Kartik1397** [run-llama/LlamaIndexTS#298]
Not sure if this is an issue with router or documentation markdowns.

![image](https://github.com/run-llama/LlamaIndexTS/assets/24036721/b5407c4d-e690-4e51-96a6-4e7c0a016aae)

https://ts.llamaindex.ai/installation.md

**Comment by marcusschiesser** [comment]
@Kartik1397 thanks a lot. Great catch! Fixed in https://github.com/run-llama/LlamaIndexTS/pull/302
