### ISSUE TITLE
Document settings do not propagate to nodes

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/LlamaIndexTS#312]
In the base `getNodesFromDocument` function, only the metadata is inherited.

This ignores other settings like `excludedLlmMetadataKeys` and other node attributes
https://github.com/run-llama/LlamaIndexTS/blob/036c00db7394614000aaa0d252eb01c7931b0cc9/packages/core/src/NodeParser.ts#L50

**Comment by techpeace** [comment]
Here's a [question I asked in the Discord about this](https://discordapp.com/channels/1059199217496772688/1133167189860565033/1192889213683765258), in case the additional context is helpful.

**Comment by techpeace** [comment]
Here's the workaround I'm using. I define a custom node parser:

```javascript
class CustomNodeParser extends SimpleNodeParser {
  /**
   * Generates an array of nodes from a document.
   * @param document - The document to generate nodes from.
   * @param textSplitter - The text splitter to use.
   * @param includeMetadata - Whether to include metadata in the nodes.
   * @param includePrevNextRel - Whether to include previous and next relationships in the nodes.
   * @returns An array of nodes.
   */
  getNodesFromDocument(
    doc,
    textSplitter,
    includeMetadata = true,
    includePrevNextRel = true
  ) {
    if (doc instanceof ImageDocument) {
      return [doc];
    }
    if (!(doc instanceof Document)) {
      throw new Error('Expected either an Image Document or Document');
    }
    const document = doc;
    const nodes = [];

    const textSplits = getTextSplitsFromDocument(document, textSplitter);

    textSplits.forEach((textSplit) => {
      const node = new TextNode({
        text: textSplit,
        metadata: includeMetadata ? document.metadata : {},
      });
      node.excludedEmbedMetadataKeys = document.excludedEmbedMetadataKeys;
      node.excludedLlmMetadataKeys = document.excludedLlmMetadataKeys;
      node.relationships[NodeRelationship.SOURCE] =
        document.asRelatedNodeInfo();
      console.log('node', node);
      nodes.push(node);
    });

    if (includePrevNextRel) {
      nodes.forEach((node, index) => {
        if (index > 0) {
          node.relationships[NodeRelationship.PREVIOUS] =
            nodes[index - 1].asRelatedNodeInfo();
        }
        if (index < nodes.length - 1) {
          node.relationships[NodeRelationship.NEXT] =
            nodes[index + 1].asRelatedNodeInfo();
        }
      });
    }

    return nodes;
  }

  /**
   * Generate Node objects from documents
   * @param documents
   */
  getNodesFromDocuments(documents) {
    console.log('getNodesFromDocuments');
    return documents
      .map((document) => this.getNodesFromDocument(document, this.textSplitter))
      .flat();
  }
}
```

In the `textSplits.forEach` block, I'm adding the properties I'm interested in:

```javascript
node.excludedEmbedMetadataKeys = document.excludedEmbedMetadataKeys;
node.excludedLlmMetadataKeys = document.excludedLlmMetadataKeys;
```

Then I define a custom service context to use the `CustomNodeParser`:

```javascript
const storageContext = await storageContextFromDefaults({ vectorStore: pgvs });
const serviceContext = serviceContextFromDefaults({
  nodeParser: new CustomNodeParser(),
});

console.debug('  - creating vector store');
const index = await VectorStoreIndex.fromDocuments(docs, {
  storageContext,
  serviceContext,
});
```

**Comment by marcusschiesser** [comment]
@techpeace Thanks a lot for the workaround. I just released version 0.0.42, which fixes this issue. Can you please try again with this latest version?

**Comment by techpeace** [comment]
@marcusschiesser Thanks so much for the quick turnaround! 🙌 I verified that the fix is working correctly in 0.0.42.

I also noticed that the requests to the OpenAI embeddings API are no longer logged by default. Is there now an option to enable request logging? I wasn't able to find it. That was how I had noticed this bug originally.

No worries if not - [HTTP Toolkit](https://httptoolkit.com/) works well for request inspection.

Thanks again!

**Comment by marcusschiesser** [comment]
You're welcome. I'm glad that it works!
We now have a `logProgress` flag that you can use, I added it for the sentence window retrieval:
https://github.com/run-llama/LlamaIndexTS/blob/555692207e1f0a3b8e444456fc8bb33558170521/examples/sentenceWindow.ts#L27

**Comment by techpeace** [comment]
I noticed that flag, which was indeed working for me, but it does not log the embedding request bodies:

<img width="307" alt="image" src="https://github.com/run-llama/LlamaIndexTS/assets/2220/c144875d-4d45-4053-85e7-81473b6534d6">

Which makes sense! I would expect `logProgress` to only log progress. But perhaps a `logRequests` flag might be helpful for some folks, as well.

As I mentioned though, using a proxy works just fine.

**Comment by marcusschiesser** [comment]
@techpeace thanks - I'll added it to our backlog :)
