### ISSUE TITLE
Llama Index TS crashes after processing more than 9 documents

### ISSUE THREAD

**Issue by preemoDez** [run-llama/LlamaIndexTS#313]
There is a simple defect related to referencing the object, instead of copying it. [Here](https://github.com/run-llama/LlamaIndexTS/blob/ddf39ebeaaeeb1c1557cbf0eec2e88afefc5ae29/packages/core/src/storage/vectorStore/utils.ts#L20) it references the `node.metadata` object and modifies it, causing the documents to grow in size exponentially. Changing:

`const metadata = node.metadata;`

to

`const metadata = {...node.metadata};`

fixes the problem.

**Comment by yisding** [comment]
Thanks for the bug report. I think we've fixed this in main now. https://github.com/run-llama/LlamaIndexTS/blob/main/packages/core/src/storage/vectorStore/utils.ts

@marcusschiesser I'm going to publish a new release.

**Comment by yisding** [comment]
OK try v0.0.41: https://www.npmjs.com/package/llamaindex/v/0.0.41

Thanks for the bug report!
