### ISSUE TITLE
Chat Engines do not provide source nodes

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/LlamaIndexTS#320]
The response from a chat engine provides no way to trace back to the source nodes used.

Can we add a hook to provide a way to cite sources?

It looks like some chat engines provide source, and others do not.

Chat engines that currently do not provide sources:
- `streamChat` in `ContextChatEngine`: https://github.com/run-llama/LlamaIndexTS/blob/85da7985388d92cb71f60f34e7d205fa142a58e3/packages/core/src/ChatEngine.ts#L333
- both `chat` and `streamChat` of `HistoryChatEngine`: https://github.com/run-llama/LlamaIndexTS/blob/85da7985388d92cb71f60f34e7d205fa142a58e3/packages/core/src/ChatEngine.ts#L430 and https://github.com/run-llama/LlamaIndexTS/blob/85da7985388d92cb71f60f34e7d205fa142a58e3/packages/core/src/ChatEngine.ts#L404

**Comment by marcusschiesser** [comment]
Fixed in llamaindex@0.0.48
