### ISSUE TITLE
MongoDB not a constructor 

### ISSUE THREAD

**Issue by alval1** [run-llama/LlamaIndexTS#321]
Getting the following error when I query with MongoDB (using next.js): 
[LlamaIndex] TypeError: mongodb__WEBPACK_IMPORTED_MODULE_1__.MongoClient is not a constructor

Beginner here, anyone know how i can debug?

**Comment by marcusschiesser** [comment]
Did you use the mongodb example created with `create-llama`? if so, can you please provide the parameters?

**Comment by nirpow** [comment]
I used create-llama tool as well
and i realize that the mongodb dependency is missing

try to run `npm i mongodb`

**Comment by alval1** [comment]
Thank you both for your help! I managed to edit the config setting with the help of GPT as a work around

**Comment by marcusschiesser** [comment]
Seems like the issue was that `mongodb` was not bundled due to https://github.com/run-llama/LlamaIndexTS/commit/a73942ddeaedb3e81c7b589caf221a76200e7d08 - latest `create-llama` should fix this issue
