### ISSUE TITLE
npm run generate has failed

### ISSUE THREAD

**Issue by khalilxg** [run-llama/LlamaIndexTS#382]
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

added 660 packages, and audited 661 packages in 1m

153 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Using OpenAI model:  gpt-3.5-turbo 

Created '.env' file. Please check the settings.

Copying test data to /home/ubuntu/Desktop/my-app7/data

Running npm run generate to generate the context data.

> my-app7@0.1.0 generate
> node app/api/chat/engine/generate.mjs

Generating storage context...
No valid data found at path: cache/doc_store.json starting new store.
No valid data found at path: cache/index_store.json starting new store.
No valid data found at path: ./cache/vector_store.json starting new store.
file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:739
            _this.data[collection][key] = _.clone(val); // Creating a shallow copy of the object
                                            ^

TypeError: _.clone is not a function
    at file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:739:45
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$K (file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:705:28)
    at _next (file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:723:17)
    at file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:728:13
    at new Promise (<anonymous>)
    at file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:720:16
    at SimpleKVStore.put (file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:743:11)
    at file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:1362:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$I (file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:1189:28)
    at _next (file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:1207:17)
    at file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:1212:13
    at new Promise (<anonymous>)
    at file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:1204:16
    at SimpleDocumentStore.setDocumentHash (file:///home/ubuntu/Desktop/my-app7/node_modules/llamaindex/dist/index.mjs:1363:11)

Node.js v20.11.0

Aborting installation.
  npm run generate has failed.

create-llama version: create-llama@0.0.14 & also @latest has same issue !!

**Comment by parhammmm** [comment]
The issue is inside `SimpleKVStore` I don't have a solution, but if it helps the console.log for lodash there doesn't have .clone. switching to `Object.assign` for shallow copy helps things move forward.

**Comment by akhoury** [comment]
@parhammmm that won't fix the issue, lodash is used in other places in the same file (`_.isNil`) and you will face the same issue. The import statement is wrong, should be `import _ from "lodash"`

https://github.com/akhoury/LlamaIndexTS/commit/416f0c466c0049b12ed07d027c0186565529898d

I will submit PR once I setup a dev env and test it
