### ISSUE TITLE
multiple js runtime support

### ISSUE THREAD

**Issue by himself65** [run-llama/LlamaIndexTS#387]
one goal of llamaindex-ts is to support multiple js environments (node, deno, edge, cloudflare worker)

- wrap nodejs internal API calls, use web standards or polyfill package
  - https://github.com/run-llama/LlamaIndexTS/pull/435
  - https://github.com/run-llama/LlamaIndexTS/pull/433
  - https://github.com/run-llama/LlamaIndexTS/pull/427
  - https://github.com/run-llama/LlamaIndexTS/pull/426
  - https://github.com/run-llama/LlamaIndexTS/pull/422
- ESM conditional export
  - https://github.com/run-llama/LlamaIndexTS/pull/451
  - https://github.com/run-llama/LlamaIndexTS/pull/443
  - https://github.com/run-llama/LlamaIndexTS/pull/401
- reduce side effects of third-party libraries
  - https://github.com/run-llama/LlamaIndexTS/pull/436
- enable ESM by default and support conditional exports
  - https://github.com/run-llama/LlamaIndexTS/pull/560

## Blocking
- https://github.com/run-llama/LlamaIndexTS/pull/384 we have to support node.js 16 for now which doesn't have `structureClone`

## Related issues

- https://github.com/run-llama/LlamaIndexTS/issues/395
- https://github.com/run-llama/LlamaIndexTS/issues/456

**Comment by himself65** [comment]
This is a long roadmap but at this time. Llamaindex has tree-shake support by using conditional import (like `import 'llamaindex/llms/Ollama'`) and this will help if the developer bundles llamaindex and distributes the app.

Further, I would try if Deno also works well

**Comment by nikolailehbrink** [comment]
Hi @himself65, thanks for the work you doing! I am following this issue, because I get a task timeout after 10s when using llamaindex-ts projects, which are deployed on vercel via nodejs runtime because of their [max duration on the hobby plan](https://vercel.com/docs/functions/runtimes#max-duration). With Edge functions this would be no problem and normally I would integrate everything via those function but as llamaindex relies on the default nodejs runtime, I can't. Do you know if there is a workaround or is there a roadmap on when to support the edge runtime? Kind regards!

**Comment by himself65** [comment]
> Hi @himself65, thanks for the work you doing! I am following this issue, because I get a task timeout after 10s when using llamaindex-ts projects, which are deployed on vercel via nodejs runtime because of their [max duration on the hobby plan](https://vercel.com/docs/functions/runtimes#max-duration). With Edge functions this would be no problem and normally I would integrate everything via those function but as llamaindex relies on the default nodejs runtime, I can't. Do you know if there is a workaround or is there a roadmap on when to support the edge runtime? Kind regards!

what's your use case? I want to know what people would use in edge runtime

**Comment by nikolailehbrink** [comment]
@himself65 Even the most standard form of create-llama with nextjs times out after 10s. I build a personal ai chat, for my portfolio website. But I guess there are a lot of use cases. Maybe not specific to edge runtime, but the node runtime restricts me on vercel, [which is the case for some folks.](https://community.openai.com/t/api-504s-in-production-vercel-only/28795/15)

**Comment by marcusschiesser** [comment]
@nikolailehbrink I just created a PR that is working with edge: https://github.com/run-llama/LlamaIndexTS/pull/618 - we're working on integrating it

**Comment by nikolailehbrink** [comment]
@marcusschiesser Very cool! I am following that issue then!

**Comment by himself65** [comment]
We can close this for now as we have release jsr/llamaindex (for deno) and @llamaindex/edge (for edge)
