### ISSUE TITLE
pdf embedding takes too long on JS !

### ISSUE THREAD

**Issue by khalilxg** [run-llama/LlamaIndexTS#394]
No valid data found at path: cache/index_store.json starting new store.
No valid data found at path: ./cache/vector_store.json starting new store.

file:///home/ubuntu/Desktop/pmp/node_modules/openai/error.mjs:58
            return new RateLimitError(status, error, message, headers);
                   ^

RateLimitError: 429 Rate limit reached for text-embedding-ada-002 in organization org-nWgo4CH4GQq60ZdZg7iFCag6 on requests per day (RPD): Limit 200, Used 200, Requested 1. Please try again in 7m12s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.
    at APIError.generate (file:///home/ubuntu/Desktop/pmp/node_modules/openai/error.mjs:58:20)
    at OpenAI.makeStatusError (file:///home/ubuntu/Desktop/pmp/node_modules/openai/core.mjs:248:25)
    at OpenAI.makeRequest (file:///home/ubuntu/Desktop/pmp/node_modules/openai/core.mjs:287:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 429,

this is create-llama latest version 0.15

the problem is npm run generate takes too long then that errror shows up, while on python full app its a matter of minute and all works fine !

**Comment by himself65** [comment]
Could you please give an example pdf to reproduce this issue?

**Comment by marcusschiesser** [comment]
@khalilxg i think the issue here is that LlamaIndexTS currently doesn't have batching
