### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by Iven2132** [run-llama/LlamaIndexTS#431]
As a person who loves the llama index Python library, LlamaIndex.ts is a piece of shit if someone doesn't want to use OpenAI LLMs. 

It will force you to use OpenAI LLMS (I broke my MacBook Screen and given for repair today), I hope you don't do the same because you will get a lot of Set OpenAI Key in OPENAI_API_KEY env variable errors and it will piss you off which can cause your computer damage and waste your money and be ready for short mental health damage because once you install this library be ready for all these things. 

Remember this library is a piece of shit don't use it if you are from a Frontend background instead of the LllamaIndex Python library which is great. 

Few things I did with my personal life and I feel stupid making this mistake because of this LlamaIndex.ts 

1: I broke my MacBook screen 
2: Said bad things to my girlfriend and friends because they just entered my room while I was figuring out how to use Llamaindex ts in Next.js.
2: Damaged my room heater
4: Broke my coffee cup
 
Of course today I am laughing at myself. 

ADVICE FOR THE CREATOR OF THIS LIBRARY: 
1: Delete this library or change its name to openaiIndex.ts 
2: Stop working with Open Source free open-source API services like Replicate and Together and write tweets about it.

**Comment by EmanuelCampos** [comment]
Hello @Iven2132, thanks for the feedbacks

Can you share with us the current snippet you’re doing to run?

The team is pushing hard to make it to achieve parity between LlamaIndexTs and the python one

Usually, it's asks for you the OPEN_AI_KEY for embeddings as well, so even if you use a different LLM it still uses OpenAI for other tasks, waiting for you answer and we'll put some effort if it's still an issue

**Comment by Iven2132** [comment]
@EmanuelCampos The Team should care more about dev experience, and make things simple don't assume that users will be geeks. 

Well, I used the create-llama CLI command to generate the template for Next.js and just tried to replace OpenAI with Together LLM. 

Code:
```
import { StreamingTextResponse } from "ai";
import { ChatMessage, MessageContent, OpenAI, TogetherEmbedding, TogetherLLM } from "llamaindex";
import { NextRequest, NextResponse } from "next/server";
import { createChatEngine } from "./engine";
import { LlamaIndexStream } from "./llamaindex-stream";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const convertMessageContent = (
  textMessage: string,
  imageUrl: string | undefined,
): MessageContent => {
  if (!imageUrl) return textMessage;
  return [
    {
      type: "text",
      text: textMessage,
    },
    {
      type: "image_url",
      image_url: {
        url: imageUrl,
      },
    },
  ];
};

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { messages, data }: { messages: ChatMessage[]; data: any } = body;
    const userMessage = messages.pop();
    if (!messages || !userMessage || userMessage.role !== "user") {
      return NextResponse.json(
        {
          error:
            "messages are required in the request body and the last message must be from the user",
        },
        { status: 400 },
      );
    }

    const llm = new TogetherLLM({
      model: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
      maxTokens: 512,
      apiKey: 'mykeyapi',
    });

    const chatEngine = await createChatEngine(llm);

    // Convert message content from Vercel/AI format to LlamaIndex/OpenAI format
    const userMessageContent = convertMessageContent(
      userMessage.content,
      data?.imageUrl,
    );

    // Calling LlamaIndex's ChatEngine to get a streamed response
    const response = await chatEngine.chat({
      message: userMessageContent,
      chatHistory: messages,
      stream: true,
    });

    // Transform LlamaIndex stream to Vercel/AI format
    const { stream, data: streamData } = LlamaIndexStream(response, {
      parserOptions: {
        image_url: data?.imageUrl,
      },
    });

    // Return a StreamingTextResponse, which can be consumed by the Vercel/AI client
    return new StreamingTextResponse(stream, {}, streamData);
  } catch (error) {
    console.error("[LlamaIndex]", error);
    return NextResponse.json(
      {
        error: (error as Error).message,
      },
      {
        status: 500,
      },
    );
  }
}
```

**Comment by logan-markewich** [comment]
@Iven2132 thanks for raising the issue. As @EmanuelCampos said, we are working to make the library better. Using open-source LLMs/models should definitely be easier.

However, this is free and open-source code, and behaving in this way is not tolerated by us. Going to to end this thread here.
