### ISSUE TITLE
Metadata Overwritten When Piping Multiple Extractors in IngestionPipeline

### ISSUE THREAD

**Issue by TYRONEMICHAEL** [run-llama/LlamaIndexTS#446]
When using the `IngestionPipeline` with multiple extractors, only the metadata from the last extractor is retained, leading to a loss of metadata added by previous extractors in the pipeline. This suggests that each extractor might be overwriting the node's metadata rather than appending to or merging with it.

## Steps to Reproduce
1. Set up an `IngestionPipeline` with multiple extractors:
    ```javascript
    const pipeline = new IngestionPipeline({
      transformations: [
        new SimpleNodeParser({ chunkSize: 200, chunkOverlap: 20 }),
        new SummaryExtractor(openaiLLM),
        new TitleExtractor(openaiLLM),
      ],
    });
    ```
2. Execute the pipeline on input data.
3. Observe that the final output contains only metadata from the last extractor.

## Expected Behavior
The pipeline should aggregate metadata from all extractors, merging them into a comprehensive metadata object for each node.

## Investigation & Potential Root Cause
Upon further investigation, a more robust approach might involve each extractor returning its metadata object, which can then be intelligently merged with existing metadata in the BaseExtractor.

This approach raises questions about handling duplicate keys. Some strategies could include:
- Overwriting with the latest value (current behavior, but may lead to data loss).
- Merging values under the same key into arrays or more complex structures, preserving all extractor contributions.
- Utilizing a conflict resolution strategy, possibly defined at the pipeline level or within each extractor.

## Additional Context
This behavior was noted in commit: [2d8845b](https://github.com/run-llama/LlamaIndexTS/commit/2d8845b0843478285e4d99a2a7cc46a57e053c9d#diff-29b991f75b30de7568949746bab50ce734c9cfb1a53e05029c90175dce73f050R394). I am considering contributing a PR to address this but am still familiarizing myself with the broader implications on the codebase. Insights or suggestions from the project maintainers would be highly valuable.

**Comment by mike-niemand** [comment]
No way... 😳 🤣

**Comment by TYRONEMICHAEL** [comment]
I tried a workaround by defining my own extractor, but I don't think the BaseExtractor is being exposed.
