### ISSUE TITLE
Mongodb Cannot destructure property '_node_content' of 'metadata' as it is undefined

### ISSUE THREAD

**Issue by Deluxer** [run-llama/LlamaIndexTS#457]
For some reason, when I perform a semantic search using MongoDB, I get an error.

```shell
Running query pipeline:  [
  {
    '$vectorSearch': {
      queryVector: [Array],
      path: 'plot_embedding',
      numCandidates: 200,
      limit: 20,
      index: 'vector-search-tutorial'
    }
  },
  { '$project': { score: [Object], plot_embedding: 0 } }
]
[Nest] 115769  - 01/26/2024, 12:28:56 PM   ERROR [ExceptionsHandler] Cannot destructure property '_node_content' of 'metadata' as it is undefined.
TypeError: Cannot destructure property '_node_content' of 'metadata' as it is undefined.
    at metadataDictToNode (/home/gerardo/ai/llamaindex-with-ollama-qa-files-js/node_modules/llamaindex/index.js:4397:28)
    at /home/gerardo/ai/llamaindex-with-ollama-qa-files-js/node_modules/llamaindex/index.js:4715:38
    at Generator.next (<anonymous>)
    at asyncGeneratorStep$I (/home/gerardo/ai/llamaindex-with-ollama-qa-files-js/node_modules/llamaindex/index.js:4603:28)
    at _next (/home/gerardo/ai/llamaindex-with-ollama-qa-files-js/node_modules/llamaindex/index.js:4621:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
``` 

I am using `MongoDBAtlasVectorSearch`.

Inside the `query` abstraction using `metadataDictToNode`.
https://github.com/run-llama/LlamaIndexTS/blob/9ce7d3d64874309570fd9bc84f1a8b5b77229861/packages/core/src/storage/vectorStore/MongoDBAtlasVectorStore.ts#L147

I don't understand how the `nodeContent` property is required to get metadata information. Maybe in the latest version it does not exist.
For additional information, my database is the default [sample data](https://www.mongodb.com/docs/atlas/sample-data/) loaded when you create your Atlas database.
https://github.com/run-llama/LlamaIndexTS/blob/9ba4547c4d0d1128a4cc025cf845213e4f72794e/packages/core/src/storage/vectorStore/utils.ts#L39
```javascript
export function metadataDictToNode(metadata: Metadata): BaseNode {
  const {
    _node_content: nodeContent,
    _node_type: nodeType,
    document_id,
    doc_id,
    ref_doc_id,
    ...rest
  } = metadata;
  if (!nodeContent) {
    throw new Error("Node content not found in metadata.");
  }
```

**Comment by marcusschiesser** [comment]
@Deluxer looks to me like you're `MongoDBAtlasVectorStore` with data wasn't generated by `MongoDBAtlasVectorStore` - where is `index: 'vector-search-tutorial'` coming from?

**Comment by Deluxer** [comment]
Yes, the data wasn't generated by MongoDBAtlasVectorStore, and that was the problem. I thought that any other vectorization could get through MongoDBAtlasVectorStore, and that was my mistake.

I tried again, generating it and getting it MongoDBAtlasVectorStore, and it works! Thank you, @marcusschiesser.
