### ISSUE TITLE
create llama templates are too many.

### ISSUE THREAD

**Issue by stmtk1** [run-llama/LlamaIndexTS#468]
There are many templates for this project. The number of templates is as many as create-llama creates.
The more options create-llama has, the more templates it will create, and therefore the more directories it will create.
It is difficult to properly manage all of those directories.
Instead of creating as many directories as there are templates, we feel that we need to find another way.

**Comment by himself65** [comment]
I think it would be better to reduce the choices, like next.js they put all templates into `/templates` folder @marcusschiesser

**Comment by marcusschiesser** [comment]
create-llama has two concepts to generate code: 
1. [`types`](https://github.com/run-llama/LlamaIndexTS/tree/main/packages/create-llama/templates/types) and 
2. [`components`](https://github.com/run-llama/LlamaIndexTS/tree/main/packages/create-llama/templates/components)

`types` are templates to scaffold whole projects (currently, there are only 5 types), and a `component` is a folder that is copied into an existing project. 

All combinations are covered by e2e tests (except vector dbs for the time being).

@himself65, both `types` and `components` are in the `/templates` folder. Next.js has fewer options and only supports `types`.

@stmtk1 let me please first understand your problem. What do you mean by there are too many templates?

**Comment by stmtk1** [comment]
I only read this line here and thought I was just copying the internals of the data directory. So I created the issue without knowing what the types directory was for.

https://github.com/run-llama/LlamaIndexTS/blob/24cb48f195338a3a89c405ded7b916313ad06d26/packages/create-llama/helpers/llama-pack.ts#L46

**Comment by stmtk1** [comment]
I only read this one line and thought I was just copying the internals of the data directory. So I created the problem without knowing what the types directory was for.

https://github.com/run-llama/LlamaIndexTS/blob/24cb48f195338a3a89c405ded7b916313ad06d26/packages/create-llama/helpers/python.ts#L140
