### ISSUE TITLE
 Ollama Embeddings

### ISSUE THREAD

**Issue by domsteil** [run-llama/LlamaIndexTS#474]
Are Ollama Embeddings available for use? For example:

` 
    async function createInMemoryVectorStore(data) {

      const embeddings = new OllamaEmbeddings({
        model: "llama2",
        baseUrl: "http://localhost:11434",
      });
      return FAISS.fromTexts(data, embeddings);
    }

`

**Comment by marcusschiesser** [comment]
yes, for usage see https://github.com/run-llama/LlamaIndexTS/blob/main/examples/ollama.ts
