### ISSUE TITLE
npx create-llama@0.0.22 fails when generating NextJS frontend for Python backend

### ISSUE THREAD

**Issue by augchan42** [run-llama/LlamaIndexTS#499]
hosermage@hosermage-x1:~/projects$ npx create-llama@latest
Need to install the following packages:
create-llama@0.0.22
Ok to proceed? (y) y
✔ What is your project named? … lifestory-llama
✔ Which template would you like to use? › Chat with streaming
✔ Which framework would you like to use? › FastAPI (Python)
✔ Would you like to generate a NextJS frontend for your FastAPI (Python) backend? … No / Yes
✔ Which UI would you like to use? › Shadcn
✔ Which model would you like to use? › gpt-3.5-turbo
✔ Which data source would you like to use? › Use an example PDF
✔ Would you like to use a vector database? › No, just store the data in the file system
✔ Please provide your OpenAI API key (leave blank to skip): … 
✔ How would you like to proceed? › Generate code and install dependencies (~2 min)
Creating a new LlamaIndex app in /home/hosermage/projects/lifestory-llama.

Initializing Python project with template: streaming 

Installing python dependencies using poetry. This may take a while...

Poetry could not find a pyproject.toml file in /home/hosermage/projects/lifestory-llama/backend or its parents
Install failed. Please install dependencies manually.

**Comment by marcusschiesser** [comment]
@augchan42 thanks for your report! It's working on my Mac - which environment are you using?

**Comment by augchan42** [comment]
I'm on ubuntu:
`
Creating a new LlamaIndex app in /home/hosermage/projects/lifestory-llama.


Initializing Python project with template: streaming

Installing python dependencies using poetry. This may take a while...

Poetry could not find a pyproject.toml file in /home/hosermage/projects/lifestory-llama/backend or its parents
Install failed. Please install dependencies manually.
npm notice
npm notice New minor version of npm available! 10.2.4 -> 10.4.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.4.0
npm notice Run npm install -g npm@10.4.0 to update!
npm notice
(.env) hosermage@LAPTOP-1RPE37PF:~/projects$ poetry --version
Poetry (version 1.7.1)
(.env) hosermage@LAPTOP-1RPE37PF:~/projects$ which poetry
/home/hosermage/.local/bin/poetry
(.env) hosermage@LAPTOP-1RPE37PF:~/projects$ uname -a
Linux LAPTOP-1RPE37PF 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
(.env) hosermage@LAPTOP-1RPE37PF:~/projects$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
(.env) hosermage@LAPTOP-1RPE37PF:~/projects$
`

**Comment by augchan42** [comment]
Issue seems to be with 0.0.22
When I install using python 3.11 and create-llama@0.0.21, the install progresses
Something got broken with the latest version.

**Comment by ivanmorales** [comment]
Confirm same error with `npx create-llama@latest` on Mac
<img width="1801" alt="image" src="https://github.com/run-llama/LlamaIndexTS/assets/244904/f8ab99a8-31a8-4ee3-b846-fa501e570ba0">

**Comment by marcusschiesser** [comment]
Sorry for the trouble, folks; I just released create-llama@0.0.24, which hopefully should work for everyone again. Please give it a spin!

Here's a bit of background on what happened:
The problem was introduced by centralizing access to the folder for the template snippets. 
Related to this, it wasn't a good idea to use `fileURLToPath(import.meta.url)` in the `ncc` build.
I had to revert that change, see https://github.com/run-llama/LlamaIndexTS/commit/4a7ac65184a83306421dafa51a7588c6bc924ce6 and upgrade ncc to version 0.38.1.

I'll keep this ticket open; please let me know if it works for you, too, and then I'll close it.

**Comment by denissopovic** [comment]
I had this problem yesterday as well but with create-llama@0.0.24 it works again.
