### ISSUE TITLE
MongoDBAtlasVectorSearch doesn't allow connection to LLM in the fromVectorStore

### ISSUE THREAD

**Issue by Deluxer** [run-llama/LlamaIndexTS#503]
MongoDB in semantic search doesn't work.

I am using Ollama and GPT-3 respectively for each case to retrieve information from MongoDB, but in the process, it's not establishing a connection to any LLM

Index configuration named "embedded_example":
```shell
{
  "fields": [
    {
      "numDimensions": 1536,
      "path": "embedding",
      "similarity": "euclidean",
      "type": "vector"
    }
  ]
}
```
Simple MongoDB configuration pointing to index name, the database was created for `MongoDBAtlasVectorSearch`.
```shell
    const vectoreStore = new MongoDBAtlasVectorSearch({
      mongodbClient: client,
      dbName: 'my_embedded',
      collectionName: 'embedded_example',
      indexName: 'embedded_example',
    });
```
For example, when I pass the connection in` VectorStoreIndex.fromDocuments` to read any document, it works, and the response is according to the information in the file (sometimes). However, when I pass the connection in `VectorStoreIndex.fromVectorStore` to retrieve data from MongoDB, it doesn't work.

```shel
Running query pipeline:  [
  {
    '$vectorSearch': {
      queryVector: [Array],
      path: 'embedding',
      numCandidates: 200,
      limit: 20,
      index: 'embedded_example'
    }
  },
  { '$project': { score: [Object], embedding: 0 } }
]
Result of query (ids): []
Empty Response
```

For some reason, it's not establishing a connection to the LLM. I know this because when I run Ollama serve, I see the POST requests in the logs when using the `fromDocuments` configuration, contrary to `fromVectorStore`, which does not show any logs.

**Comment by marcusschiesser** [comment]
I am not sure if I understand the issue entirely, but `VectorStoreIndex.fromVectorStore` is not calculating any embeddings (contrary to `VectorStoreIndex.fromDocuments`). It's used to consume the data in the vector store, see https://github.com/run-llama/LlamaIndexTS/blob/main/examples/mongodb/3_query.ts#L23

So first, you use `VectorStoreIndex.fromDocuments` to load the data (or the new [ingestion pipeline](https://ts.llamaindex.ai/modules/ingestion_pipeline/)) and then `VectorStoreIndex.fromVectorStore` to query the data.

You must ensure that the `embedModel` of the service context is the same for both steps. How do you generate your `serviceContext`?

**Comment by Deluxer** [comment]
Sorry for the confusion. Leaving aside my explanation, I only try to use the example in [3_query.ts](https://github.com/run-llama/LlamaIndexTS/blob/main/examples/mongodb/3_query.ts), but I don't get any records.

I had configured MongoDB connection, created indexes, ada-2 to populate the database, and used GPT-3 to retrieve records, however the response is an `Empty Response`. I've done numerous tests, but it doesn't works.
```shell
Result of query (ids): []
Empty Response
```

**Comment by marcusschiesser** [comment]
@Deluxer let's entangle the problem:

What happens if you just use the retriever:
```
const retriever = index.asRetriever({ similarityTopK: 20 });
const response = retriever.retrieve(query);
```

**Comment by Deluxer** [comment]
I already tested what you recommended me, but It's not working yet, I am working on this in a Nestjs project.

```shell
{
  my_configurations: {
    nodeParse: SimpleNodeParser {
      textSplitter: [SentenceSplitter],
      includeMetadata: true,
      includePrevNextRel: true
    },
    embed: OpenAIEmbedding {
      apiKey: undefined,
      model: 'text-embedding-ada-002',
      dimensions: undefined,
      maxRetries: 10,
      timeout: 60000,
      additionalSessionOptions: undefined,
      session: [OpenAISession]
    },
    llm: OpenAI {
      apiKey: undefined,
      model: 'gpt-3.5-turbo',
      temperature: 0.1,
      topP: 1,
      maxTokens: undefined,
      maxRetries: 10,
      timeout: 60000,
      additionalChatOptions: undefined,
      additionalSessionOptions: undefined,
      session: [OpenAISession],
      callbackManager: undefined
    },
    template: PromptHelper {
      contextWindow: 3900,
      numOutput: 256,
      chunkOverlapRatio: 0.1,
      separator: ' ',
      chunkSizeLimit: undefined,
      tokenizer: [Function: bound encode]
    }
  }
}
Running query pipeline:  [
  {
    '$vectorSearch': {
      queryVector: [Array],
      path: 'embedding',
      numCandidates: 200,
      limit: 20,
      index: 'embedded_example'
    }
  },
  { '$project': { score: [Object], embedding: 0 } }
]
Result of query (ids): []
[]
```

**Comment by marcusschiesser** [comment]
I see you're now using OpenAI and you're also using a different index name (`'embedded_example'`)- Did you try running the whole MongoDB example: https://github.com/run-llama/LlamaIndexTS/blob/main/examples/mongodb ? It that works, you can change one thing at a time (e.g., just the LLM)

**Comment by Deluxer** [comment]
Currently, it already works in a NestJS project. Thank you @marcusschiesser

**Comment by marcusschiesser** [comment]
Are you using Edge runtime? Then you need to directly import the MongoDB vector store using
```
import { MongoDBAtlasVectorSearch } from "llamaindex/storage/vectorStore/MongoDBAtlasVectorStore";
```
