### ISSUE TITLE
create-llama: FastAPI reloads custom HuggingFaceLLM on every chat call.

### ISSUE THREAD

**Issue by BastianSpatz** [run-llama/LlamaIndexTS#548]
This may be a stupid question, but I've been fighting with adding a custom LLM. 

I can generate the vector storage and chat with the HuggingFaceLLM, but every time I call the chat endpoint the FastAPI Depends reloads the whole index including my model from disk.

Has anyone maybe already solved this and can point me in the right direction?

**Comment by EmanuelCampos** [comment]
@BastianSpatz can you share your code? then we can help you better

**Comment by marcusschiesser** [comment]
@BastianSpatz yes, depends is called for every request. It's not the best code, but can you try:
```python
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
model = "path-to-llama-2-7b-chat-hf"
llm = HuggingFaceLLM(
        model_name=model,
        tokenizer_name=model,
        max_new_tokens=1024,
        # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
        context_window=3900,
        # kwargs to pass to __call__()
        generate_kwargs={},
        # kwargs to pass to __init__()
        model_kwargs={ }, 
        device_map="auto",
)

def create_base_context():
    return ServiceContext.from_defaults(llm=llm, embed_model=embed_model)
```

**Comment by BastianSpatz** [comment]
Thank you for the help. This works and now only loads the model once. It still loads the index again everytime i ask a question. But I think this makes sense and I can use the same principle here if i want to only load it once.
```
INFO:     Loading index from storage...
INFO:     Finished loading index from storage
INFO:     127.0.0.1:54476 - "POST /api/chat HTTP/1.1" 200 OK
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
INFO:     Loading index from storage...
INFO:     Finished loading index from storage
INFO:     127.0.0.1:53308 - "POST /api/chat HTTP/1.1" 200 OK
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
```

**Comment by marcusschiesser** [comment]
@BastianSpatz Great that it works. Yes, the design of the generated API is stateless, which makes sense if you want to scale the deployments and you're using a vector database instead of the file system
