### ISSUE TITLE
Cannot provide system prompt with `OpenAIAgent`

### ISSUE THREAD

**Issue by Aryik** [run-llama/LlamaIndexTS#557]
If you create an `OpenAIAgent` like this, `llamaindex` will throw an exception: 
```
  const agent = new OpenAIAgent({
    tools: [],
    verbose: true,
    systemPrompt,
  });
```

This is the exception: 
```
Error: Cannot provide both systemPrompt and prefixMessages
    at new OpenAIAgent (node_modules/llamaindex/index.js:3953:23)
```

This is because in the constructor, you're doing `prefixMessages = prefixMessages || []`, and then you are throwing an exception if `systemPrompt` is passed in and `prefixMessages` is truthy: https://github.com/run-llama/LlamaIndexTS/blob/d4eda9f3965969d89d396e26d04fcaf2529f9431/packages/core/src/agent/openai/base.ts#L44

`prefixMessages` will always be truthy because of the `|| []`.

**Comment by marcusschiesser** [comment]
@EmanuelCampos can you have a look please?

**Comment by rawwerks** [comment]
related, but for queryEngine: https://github.com/run-llama/LlamaIndexTS/issues/606
