### ISSUE TITLE
All API documentation pages respond with a 404 Page Not Found

### ISSUE THREAD

**Issue by simonplend** [run-llama/LlamaIndexTS#565]
As far as I can tell, all API documentation pages respond with a 404 Page Not Found.

## Steps to reproduce

1. Visit https://ts.llamaindex.ai/
1. Search for `ChromaVectorStore`
1. Click on any of the results
1. You'll be taken to a URL like `https://ts.llamaindex.ai/api/classes/ChromaVectorStore` which responds with a 404 Page Not Found.

All of the 'API Reference' links throughout the documentation seem to be broken too e.g.

- https://ts.llamaindex.ai/api/classes/RetrieverQueryEngine
- https://ts.llamaindex.ai/api/classes/SubQuestionQueryEngine
- https://ts.llamaindex.ai/api/interfaces/QueryEngineTool.md

**Comment by EmanuelCampos** [comment]
Solved on #569

The built is being made

thanks for the report

**Comment by simonplend** [comment]
@EmanuelCampos Great — thanks for the quick fix!
