### ISSUE TITLE
SimpleDirectoryReader recursive load documents

### ISSUE THREAD

**Issue by jmiddleton** [run-llama/LlamaIndexTS#647]
In the same way as SimpleDirectoryReader in python it would be good if SimpleDirectoryReader can support the recursive parameter.

**Comment by marcusschiesser** [comment]
In LlamaIndexTS, the `SimpleDirectoryReader` should recursively load documents. Can you please share your code and directory structure, so I can have a look at?

**Comment by jmiddleton** [comment]
Hi Marcus,

I created a project with create-llama npm and then in the file generate.mjs I saw the below code:

const documents = await new SimpleDirectoryReader().loadData({
      directoryPath: STORAGE_DIR,
    });

Then, I checked the method loadData and I can see one method received the below class. I was hoping to see something like in python version “recursive” but i couldn’t find it.

export type SimpleDirectoryReaderLoadDataParams = {
    directoryPath: string;
    fs?: CompleteFileSystem;
    defaultReader?: BaseReader | null;
    fileExtToReader?: Record<string, BaseReader>;
};

**Comment by marcusschiesser** [comment]
That's correct. The `recursive` parameter is only in Python. LlamaIndexTS processes all subdirectories recursively by default. 

This is done by calling the `walk` function, see https://github.com/run-llama/LlamaIndexTS/blob/fececd89ab8dc9fee5bf57f26819a63c32cca51a/packages/core/src/storage/FileSystem.ts#L28

**Comment by jmiddleton** [comment]
Thanks for clarifying this.Kind Regards,Jorge MiddletonOn 22 Mar 2024, at 7:47 pm, Marcus Schiesser ***@***.***> wrote:﻿
That's correct. The recursive parameter is only in Python. LlamaIndexTS processes all subdirectories recursively by default.
This is done by calling the walk function, see https://github.com/run-llama/LlamaIndexTS/blob/fececd89ab8dc9fee5bf57f26819a63c32cca51a/packages/core/src/storage/FileSystem.ts#L28
