### ISSUE TITLE
Metadata Filtering Not Working with Astra DataStax Vector Database

### ISSUE THREAD

**Issue by israa-junaid** [run-llama/LlamaIndexTS#651]
### Description:
I'm encountering a problem with metadata filtering when using the Astra DataStax vector store with the latest version of the llamaindex TypeScript package. My goal is to execute queries based on the **fileId** metadata, but I'm consistently receiving an empty response, indicating that the filtering might not be functioning as expected.

Following is my code :
```
      const astraVS = new AstraDBVectorStore();
        await astraVS.connect(collectionName);
        const ctx = serviceContextFromDefaults();
        const index = await VectorStoreIndex.fromVectorStore(astraVS, ctx);
        const dynamicPrompt = createPrompt(query, LlamaContext);
        const retriever = await index.asRetriever({ similarityTopK: 2 });
        const queryEngine = index.asQueryEngine({
            retriever,
            preFilters: {
                filters: [
                    {
                        key: "fileId",
                        value: "DuO03qLWa12sbifyEndf",
                        filterType: "ExactMatch",
                    },
                ],
            },
        });
        const result = await queryEngine.query({
            query: 'who is trespasser',
        });
```
 Getting empty response, even when following the official documentation's examples with Astra Datastax.

**Comment by marcusschiesser** [comment]
I just checked that filters are implemented on the `AstraDBVectorStore`. @mfortman11 As you implemented it, can you please have a look?

**Comment by mfortman11** [comment]
@israa-junaid sorry for not seeing this earlier.  Are you able to filter your content in [Astra](astra.datastax.com)?

<img width="1373" alt="Screen Shot 2024-03-20 at 9 21 50 AM" src="https://github.com/run-llama/LlamaIndexTS/assets/6100513/065e6885-ce44-40c0-9fad-36abd4840ed4">

I was able to filter properly here using [this sample dataset](https://astra-vector-loader-sample-datasets.s3.amazonaws.com/movie_openai_100.csv) (I just had to set the `contentKey` accordingly)

 ```typescript
  const astraVS = new AstraDBVectorStore({
    contentKey: 'reviewtext',
  });
  await astraVS.connect('movie_reviews');
  const ctx = serviceContextFromDefaults();
  const index = await VectorStoreIndex.fromVectorStore(astraVS, ctx);
  const retriever = await index.asRetriever({ similarityTopK: 2 });
  const queryEngine = index.asQueryEngine({
      retriever,
      preFilters: {
          filters: [
              {
                  key: "title",
                  value: "Small Town Wisconsin",
                  filterType: "ExactMatch",
              },
          ],
      },
  });
  const result = await queryEngine.query({
      query: 'what was the cast like?',
  });

  console.log(result.response);
  console.log(result.sourceNodes);
```

Response: `'The cast was accomplished and committed.'`

**Comment by israa-junaid** [comment]
@mfortman11 ,Yes I'm able to filter my content in Astra.  
![image](https://github.com/run-llama/LlamaIndexTS/assets/63905901/60c0a3f6-0ed7-496c-a404-33214bc661ca)
I tried running my code using the `contentKey `still getting the same empty response. Here is my code for reference 
`async function main() {
  try {
    const astraVS = new AstraDBVectorStore({
      contentKey: 'reviewdogs',
    });
    await astraVS.connect(collectionName);
    const ctx = serviceContextFromDefaults();
    const index = await VectorStoreIndex.fromVectorStore(astraVS, ctx);
    const retriever = await index.asRetriever({ similarityTopK: 2 });
    const queryEngine = index.asQueryEngine({
        retriever,
        preFilters: {
            filters: [
                {
                    key: "dogId",
                    value: "1",
                    filterType: "ExactMatch",
                },
            ],
        },
    });
    const result = await queryEngine.query({
        query: 'what is the color of dog ?',
    });
    console.log(result.response);
  } catch (e) {
    console.error(e);
  }
}`

**Comment by mfortman11** [comment]
@israa-junaid for the time being use `metadata.<your field>` as the key for your filter

There seems to be some different implementations of how metadata is handled among these vector stores so I'll look into this and PR some changes but the above solution will suffice for now.
