### ISSUE TITLE
Async Local Storage for global Settings

### ISSUE THREAD

**Issue by EmanuelCampos** [run-llama/LlamaIndexTS#671]
https://nodejs.org/docs/latest/api/async_context.html#class-asynclocalstorage

P.S. Even though this is node.js API, but deno, bun, and vercel edge runtime all support this

_Originally posted by @himself65 in https://github.com/run-llama/LlamaIndexTS/pull/668#discussion_r1542166013_

**Comment by himself65** [comment]
My expected API would be like

```ts
import { Settings } from 'llamaindex'

Settings.runWithLLM(async () => {
  // will use this llm instance
}, llm)
```

**Comment by himself65** [comment]
Some upstream issue: https://github.com/denoland/deno/pull/23175
