### ISSUE TITLE
Add support for HuggingFace LLM Inference 

### ISSUE THREAD

**Issue by tasmay** [run-llama/LlamaIndexTS#686]
I'm trying to build a fullstack RAG application with LlamaIndex TS. I don't want to use create-llama as it keeps asking for OpenAI API Key which I don't intend to use as the underlying LLM. Is there any support for HuggingFaceInferenceAPI in LlamaIndexTS as there is in the python version?

**Comment by himself65** [comment]
See: https://ts.llamaindex.ai/modules/embeddings/available_embeddings/huggingface

**Comment by tasmay** [comment]
> See: https://ts.llamaindex.ai/modules/embeddings/available_embeddings/huggingface

Thanks for your reply. But the code still requires me to provide an OpenAI API key. Is that mandatory to provide? I don't intend to use OpenAI as underlying LLM. I want to call the HuggingFaceInferenceAPI like it's done here https://docs.llamaindex.ai/en/stable/examples/llm/huggingface/ but I want to achieve the same in Typescript. Is that even possible?

**Comment by marcusschiesser** [comment]
@tasmay Currently, we're not supporting HuggingFace for LLM inference in Typescript (you're referencing the Python version that supports it), but we support a lot of other LLMs besides OpenAI in Typescript; see https://ts.llamaindex.ai/modules/llms/ 

 You just have to replace the `OpenAI` class with one of these classes in the code generated by `create-llama` (or generate Python code (FastAPI) with `create-llama`).

I'll change the title of this issue to add support for HF LLM

**Comment by tasmay** [comment]
Thanks, @marcusschiesser. That answers my question!

**Comment by himself65** [comment]
maybe related https://github.com/run-llama/LlamaIndexTS/commit/d10533ef7706ab539a229298cec73939375bf09f

**Comment by marcusschiesser** [comment]
@tasmay in 0.3.4, you can now use `HuggingFaceInferenceAPI`, see:

https://github.com/run-llama/LlamaIndexTS/blob/f1862ccab192209b2679c2a7088b35d76707303f/examples/huggingface/chat.ts#L1-L22

**Comment by tasmay** [comment]
Thanks @marcusschiesser! This is really helpful.
