### ISSUE TITLE
OpenAIAgent verbose parameter

### ISSUE THREAD

**Issue by unseen1980** [run-llama/LlamaIndexTS#724]
Hello, I would like to see metadata related to tools and when I try to use the verbose parameter as per documentation I am getting an error:

```
agent-test.ts:51:5 - error TS2353: Object literal may only specify known properties, and 'verbose' does not exist in type 'OpenAIAgentParams'.
51     verbose: true,
```

<img width="1072" alt="Screenshot 2024-04-16 at 11 30 51" src="https://github.com/run-llama/LlamaIndexTS/assets/2386570/f558200f-c61c-43b9-ae23-0db8df0989c5">

Is there any change in the API ? I am using this example here https://ts.llamaindex.ai/modules/agent/openai

Thanks a lot

**Comment by himself65** [comment]
you should use `DEBUG=llamaindex ...` instead
