### ISSUE TITLE
Question - JSON Support

### ISSUE THREAD

**Issue by sabatale** [run-llama/LlamaIndexTS#73]
### Details

Great library! We understand JSON is not yet supported in the way it is in Python.

However, do you know if there is a workaround to create a Document that can interpret it as-is?

```
  var jsonData = {
    "macros": [
      {
        "value": "Hey, ABC...",
        "title": "ABC"
      },
      {
        "value": "Hey, DEF...",
        "title": "DEF"
      },
    ...}

    const nodes = getNodesFromDocument(
      new Document({ text: jsonData }),  // tried jsonData.toString()
      new SentenceSplitter(1024, 20),
    );

    const nodesWithEmbeddings = await VectorStoreIndex.getNodeEmbeddingResults(
      nodes,
      serviceContextFromDefaults(),
      true,
    );

   ...

   const query = "Answer only with the macro value I should use to reply to this text: ...";
   const result = await queryEngine.query(query);
```

The answer is pretty much always: ```{ "reply": "macro_1" }```. When converted to text, such as "Macro: Hey, ABC.\nMacro: Hey, DEF.", it works fine. Can we assume the sourceNodes' `metadataSeparator` is the culprit here? It seems to work on the playground demo though.

Cheers,

<details>
<summary>Checklist</summary>

- [X] `packages/core/src/JsonDocument.ts`
> * Define a new class JsonDocument that extends the Document class.
> • In the constructor, take a JSON object as input and store it in a suitable format.
> • Override the necessary methods of the Document class to handle JSON data.

- [X] `packages/core/src/NodeParser.ts`
> * Modify the getNodesFromDocument function to check if the document is an instance of JsonDocument.
> • If it is, parse the JSON data and generate nodes accordingly.

- [X] `packages/core/src/ResponseSynthesizer.ts`
> * Modify the synthesize method to handle nodes generated from JSON data.

- [X] `packages/core/src/indices/list/ListIndex.ts`
> * Modify the fromDocuments method to handle documents that are instances of JsonDocument.

- [ ] `packages/core/src/OutputParser.ts`
> * Modify the parse and format methods of the SubQuestionOutputParser class to handle output related to JSON data.

</details>

**Comment by yisding** [comment]
Try JSON.stringify(jsonData, null, 2) and see if it does better.

In general, JSON will perform worse on embedding search performance, so if you can convert to text I would do so. Happy to discuss this further as this is an area that I've looked into quite a bit.
