### ISSUE TITLE
Missing source node from TextNode

### ISSUE THREAD

**Issue by sabatale** [run-llama/LlamaIndexTS#77]
### Details

We noticed the error "Missing source node from TextNode" a lot after getting each embedding.

After looking in this repo and the original Python, we did not really found anything.

It does not seem to affect the results though. Can you help clarify the issue?

We initially though this may be linked to MetadataMode, but it's not.

```
﻿getting embedding for node 0/3
﻿getting embedding for node 1/3
﻿getting embedding for node 2/3
﻿Missing source node from TextNode.
﻿Missing source node from TextNode.
﻿Missing source node from TextNode.
```

```
const nodes = getNodesFromDocument(
  new Document({ text: doc }),
  new SentenceSplitter(split0, split1),
);

const nodesWithEmbeddings = await VectorStoreIndex.getNodeEmbeddingResults(
  nodes,
  serviceContextFromDefaults(),
  true,
);

var embed = nodesWithEmbeddings.map((nodeWithEmbedding) => ({
  text: nodeWithEmbedding.node.getContent(MetadataMode.NONE),
  embedding: nodeWithEmbedding.embedding,
}));

const embeddingResults = embed.map((config) => {
  return {
    node: new TextNode({ text: config.text }),
    embedding: config.embedding,
  };
});
const indexDict = new IndexDict();
for (const { node } of embeddingResults) {
  indexDict.addNode(node);
}

const index = await VectorStoreIndex.init({
  indexStruct: indexDict,
  serviceContext: serviceContextFromDefaults({
    llm: new OpenAI({ apiKey: openaikey, model: llmodel, temperature: temperature, topP: topP }),
  }),
});

index.vectorStore.add(embeddingResults);
if (!index.vectorStore.storesText) {
  await index.docStore.addDocuments(
    embeddingResults.map((result) => result.node),
    true,
  );
}
await index.indexStore?.addIndexStruct(indexDict);
index.indexStruct = indexDict;

const retriever = index.asRetriever();
retriever.similarityTopK = topK;

const queryEngine = new RetrieverQueryEngine(retriever);

const result = await queryEngine.query(query);
```

<details>
<summary>Checklist</summary>

- [X] `packages/core/src/Node.ts`
> * Add a new property to the TextNode class called sourceNode. This property should be of type Node and should be optional.
> • Modify the constructor of the TextNode class to accept an additional parameter called sourceNode. This parameter should be of type Node and should be optional.
> • In the constructor of the TextNode class, set the sourceNode property to the value of the sourceNode parameter.
> • Modify the code where the TextNode instances are created to pass in the source node when creating the new TextNode instances.

</details>

**Comment by yisding** [comment]
Hi! So the source node is a reference between the document and the splits. In your use case it doesn't really matter so I would just ignore the error. If you really care you need to add the document to the vector store along with the splits. You can do that with fromDocuments or lower level. (happy to show you some example code if need be)

**Comment by sabatale** [comment]
If you have an example, that'd be great for posterity. Thanks a lot!
