### ISSUE TITLE
Evaluator broken

### ISSUE THREAD

**Issue by jzhao62** [run-llama/LlamaIndexTS#813]
- [Correctness evaluator](https://ts.llamaindex.ai/modules/evaluation/modules/correctness) broken 
- tried sample code snippets in the wiki
- looks like the response var no longer support string 
![Screenshot_20240506_134334](https://github.com/run-llama/LlamaIndexTS/assets/25937657/277ff99d-f008-4024-b3a9-07570d499a7a)
![image](https://github.com/run-llama/LlamaIndexTS/assets/25937657/90e38035-6713-43cb-9971-0d221ce3ca79)

**Comment by marcusschiesser** [comment]
@jzhao62 thanks for pointing out. Should be fixed in https://github.com/run-llama/LlamaIndexTS/pull/913
