### ISSUE TITLE
Sweep: Adding metadata when loading documents from JSON

### ISSUE THREAD

**Issue by marcagve18** [run-llama/LlamaIndexTS#83]
### Details

Hey!

Right now, when you load a document of a set of nodes from a storage context the metadata field is empty. I guess it is missing here in this function.

Thx!
![Screenshot 2023-08-18 at 14 03 01](https://github.com/run-llama/LlamaIndexTS/assets/78203527/a7cc6855-d2b5-4c7a-a04c-2debe893cddd)

<details>
<summary>Checklist</summary>

- [X] `packages/core/src/storage/docStore/SimpleDocumentStore.ts`
> • Add a new parameter to the `load` function to accept metadata. The parameter should be an object with keys and values corresponding to the metadata.
> • Inside the `load` function, after the documents or nodes are loaded, assign the metadata to them. This can be done by looping over the documents or nodes and setting their `metadata` property to the provided metadata.

- [X] `packages/core/src/storage/docStore/SimpleDocumentStore.ts`
> • Modify the `save` function to also save the metadata of the documents or nodes. This can be done by including the metadata in the data that is written to the storage.

- [X] `packages/core/src/storage/StorageContext.ts`
> • Modify the `getDocuments` and `getNodes` functions to also return the metadata of the documents or nodes. This can be done by including the metadata in the objects that are returned by these functions.

</details>

**Comment by yisding** [comment]
This should be taken care of in 0.0.21. Thanks for the report!
