### ISSUE TITLE
Sweep: Stream OpenAI responses

### ISSUE THREAD

**Issue by tbo** [run-llama/LlamaIndexTS#86]
### Details

Version 4 of the `openai` package allows streaming responses:

https://github.com/openai/openai-node#streaming-responses

Would it be possible to utilize streaming with the Query/Chat engine?

<details>
<summary>Checklist</summary>

- [X] `packages/core/src/llm/LLM.ts`
> • In the OpenAI class, modify the chat method to support streaming responses. Specifically, when calling the chat.completions.create method of the OpenAI API, set the stream parameter to true.
> • Still in the chat method, after calling the chat.completions.create method, pass the response to the handleOpenAIStream function. This function will handle the streaming response and return the final result.

</details>

**Comment by yisding** [comment]
Hi @tbo we currently do support streaming with the CallbackManager's onLLMStream callback function but we're going to do some more work this week to align the streaming support with the OpenAI/Anthropic/Replicate functionality.

**Comment by ymohamed08** [comment]
Just wanted to ask about the streaming functionality, if there are any examples provided in the documentation for implementing the onLLMStream or using the high level function and just calling streaming = True. 
Thank you for what you are doing btw 😊

**Comment by EmanuelCampos** [comment]
Closing due inactivity and for cleaning

Feel free to open again
