### ISSUE TITLE
Possible issue with chunkSizeCheck decorator

### ISSUE THREAD

**Issue by garviand** [run-llama/LlamaIndexTS#879]
It seems like `node.getContent(metadataMode: MetadataMode)` always returns content with `MetadataMode.NONE`. I looked into it and I think `@chunkSizeCheck` is causing this.

I'm wondering if

```
export function chunkSizeCheck(
  contentGetter: () => string,
  _context: ClassMethodDecoratorContext | ClassGetterDecoratorContext,
) {
  return function <Node extends BaseNode>(this: Node) {
    const content = contentGetter.call(this);
```

Should be changed to something like

```
export function chunkSizeCheck(
  contentGetter: (metadataMode: MetadataMode) => string,
  _context: ClassMethodDecoratorContext | ClassGetterDecoratorContext,
) {
  return function <Node extends BaseNode>(
    this: Node,
    metadataMode: MetadataMode,
  ) {
    const content = contentGetter.call(this, metadataMode);
```

To test:

Call `node.getContent(MetadataMode.LLM)` or any other MetadataMode

Let me know if I'm not understanding this correctly. If it is an issue, I'm happy to submit a PR.

**Comment by Tibiritabara** [comment]
I am also facing the same issue. MetadataMode being changed to either `EMBED` or `ALL` it is always returning metadata `NONE`.

**Comment by marcusschiesser** [comment]
fixed with https://github.com/run-llama/LlamaIndexTS/pull/891/files
