### ISSUE TITLE
feat: add support for azure dynamic session tool

### ISSUE THREAD

**Issue by manekinekko** [run-llama/LlamaIndexTS#941]
We'd love to add a new tool that provides a Python code interpreter tool using code interpreter sandboxes in [Azure Container Apps dynamic sessions](https://learn.microsoft.com/azure/container-apps/sessions).

cc @yisding @seldo @anthonychu

**Comment by himself65** [comment]
yi is no longer maintaining this repo you can ping me or @marcusschiesser

**Comment by manekinekko** [comment]
Thank you @himself65. Actually, Marcus is already reviewing the PR :)

**Comment by parhammmm** [comment]
@manekinekko a question maybe you'll know. I'm trying to use a session and everything is working fine with one endpoint I'm using for testing but getting a 403 in prod. 

I know this is a vague question but would you know where I can get started looking? Seems like a configuration somewhere I cannot pinpoint

**Comment by manekinekko** [comment]
Yes, correct @parhammmm! 403 means missing or wrong roles. Lmk if you managed to fix it. I am working on a sample app demonstrating llamaindex and code interpreter with Azure dyn sessions. Should be ready in coming weeks.

**Comment by parhammmm** [comment]
@manekinekko yep that was it! I have that running with a few LLMs. It's working pretty well with agents

**Comment by manekinekko** [comment]
Wonderful!! Would love to have your feedback on the Dynamic Session API (missing features, speed, etc) anything you have in mind 😀

**Comment by parhammmm** [comment]
Honestly it's complete for our use case, speed is quite good too. Custom containers support would be nice which we'll probably need in the near future but that's it, in the docs it mentions it's available but on the azure dash it's not possible - so I'm assuming it's pending role out.

Oh although a bit of a nitpick and not critical a nice to have would be terraform support, right now we're adding it manually.

Thanks again!

**Comment by marcusschiesser** [comment]
@manekinekko 
>I am working on a sample app demonstrating llamaindex and code interpreter with Azure dyn sessions. Should be ready in coming weeks.
Are you interested in using https://github.com/run-llama/create-llama ? I anyhow have on my list adding support for your tool

**Comment by manekinekko** [comment]
ofc, I am already using this great tool as the base for our samples. Let me know if you need help.

**Comment by marcusschiesser** [comment]
@manekinekko great! we already have some code, I'll prepare a PR, and we can work on it together

**Comment by marcusschiesser** [comment]
@manekinekko We're started working on a PR (https://github.com/run-llama/create-llama/pull/158) it's adding the tool for Python - you might want to test that first, we'll add a TS version in the next days.
