### ISSUE TITLE
bug: fail to compile app with llamaindex v0.4.0 

### ISSUE THREAD

**Issue by manekinekko** [run-llama/LlamaIndexTS#951]
After upgrading to [llamaindex v0.4.0](https://github.com/run-llama/LlamaIndexTS/releases/tag/llamaindex%400.4.0), Next app fails to build with following errors (see full logs [here](https://github.com/Azure-Samples/llama-index-javascript/actions/runs/9610779460/job/26507967816)):

```
./node_modules/llamaindex/dist/ChatHistory.js
Attempted import error: 'tokenizers' is not exported from '@llamaindex/env' (imported as 'tokenizers').
Import trace for requested module:
./node_modules/llamaindex/dist/ChatHistory.js
./node_modules/llamaindex/dist/index.edge.js
./node_modules/llamaindex/dist/index.react-server.js
./app/api/chat/route.ts
./node_modules/llamaindex/dist/PromptHelper.js
Attempted import error: 'tokenizers' is not exported from '@llamaindex/env' (imported as 'tokenizers').
Import trace for requested module:
./node_modules/llamaindex/dist/PromptHelper.js
./node_modules/llamaindex/dist/index.edge.js
./node_modules/llamaindex/dist/index.react-server.js
./app/api/chat/route.ts
./node_modules/llamaindex/dist/TextSplitter.js
Attempted import error: 'tokenizers' is not exported from '@llamaindex/env' (imported as 'tokenizers').
Import trace for requested module:
./node_modules/llamaindex/dist/TextSplitter.js
./node_modules/llamaindex/dist/index.edge.js
./node_modules/llamaindex/dist/index.react-server.js
./app/api/chat/route.ts
./node_modules/llamaindex/dist/embeddings/OpenAIEmbedding.js
Attempted import error: 'Tokenizers' is not exported from '@llamaindex/env' (imported as 'Tokenizers').
...
```

**Comment by parhammmm** [comment]
@marcusschiesser  @himself65  it's because https://www.npmjs.com/package/@llamaindex/env needs to be published

**Comment by parhammmm** [comment]
@manekinekko for your dev environment you can `npm install /path/to/LlamaIndexTS/packages/llamaindex` in the meantime

**Comment by marcusschiesser** [comment]
@parhammmm and @manekinekko great catch! That's the problem if your always using the local packages :D - Sorry about that. Just released v0.4.1 with the @env package included - Please have a try again

**Comment by manekinekko** [comment]
Thanks @marcusschiesser. That did indeed fix the origin issue. 

However, now I am having other issues with missing (or remaned) types. It's worth mentioning that I am using the Next.js sample built by [create-llama](https://www.npmjs.com/package/create-llama) package which probably needs to be updated.
![image](https://github.com/run-llama/LlamaIndexTS/assets/1699357/1bb727d3-cf23-4f95-9bef-e49a7eeb39d4)

![image](https://github.com/run-llama/LlamaIndexTS/assets/1699357/e63562ef-a4ac-4d0b-aac7-4c643c375c36)

**Comment by parhammmm** [comment]
try `EngineResponse`  instead of `Response`. I'm not sure what `AgentStreamChatResponse` as it's gone is but `ReadableStream<EngineResponse>` seems like your best bet

**Comment by manekinekko** [comment]
Thank you @parhammmm  and @marcusschiesser !! Our [sample app](https://github.com/Azure-Samples/llama-index-javascript) is now building successfully. 

@seldo you can try again the app, it should build now 😃

**Comment by parhammmm** [comment]
@marcusschiesser can we also republish the `@llamaindex/community` package with the 0.4.1?
