### ISSUE TITLE
Sweep: did the pptx loader and query supported ? if yes  i can't see it in the docs

### ISSUE THREAD

**Issue by Kmounier** [run-llama/LlamaIndexTS#96]
<details open>
<summary>Checklist</summary>

- [X] `packages/core/src/readers/PptxReader.ts`
> • Create a new class called PptxReader that extends the base reader class.
> • Implement a method in the PptxReader class that can read pptx files and convert them into a format that can be indexed and queried by the LlamaIndexTS project.

- [ ] `packages/core/src/QueryEngine.ts`
> • Modify the QueryEngine class to handle the format that pptx files are converted into by the PptxReader class.
> • This will involve adding a new case to the switch statement in the query method that handles pptx files.

- [X] `apps/docs/docusaurus.config.js`
> • Update the documentation to include information about pptx support.
> • This will involve adding a new section to the documentation that explains how to load pptx files and how to query them.

- [X] `packages/core/src/tests/PptxReader.test.ts`
> • Create a new test file for the PptxReader class.
> • Implement tests that specifically test the loading and querying of pptx files.

</details>

**Comment by EmanuelCampos** [comment]
Closing due inactivity and for cleaning

Feel free to open again
