### ISSUE TITLE
Request | Make it possible to configure a remote Ollama host/baseURL

### ISSUE THREAD

**Issue by aweijnitz** [run-llama/LlamaIndexTS#990]
Currently the Ollama class assumes Ollama is running on localhost. This is an unnecessary limitation. 
The `config` object is not passed down to the "native wrapper" although it looks like it in the code and thus, it defaults to localhost and port.

As a developer, I would like to supply a host and port to be used when creating my Ollama instance. 

Example of intended use (see config object)
```
Settings.llm = new Ollama({ 
    model: models[modelIndex],
    temperature: 0.75,
    config: {
      host: 'http://my.own.internal.hostname.de:${CUSTOM_PORT}/'
    }
  })
```

The "native wrapper" class where the config object never arrives:

https://github.com/run-llama/LlamaIndexTS/blob/41fe871e2fcd42e0dda0678de1e1b25b1f1dec7f/packages/llamaindex/src/internal/deps/ollama.js#L274

**Comment by gcapozzo** [comment]
Set this in the .env file:
`OLLAMA_BASE_URL=http://IP:PORT`

**Comment by himself65** [comment]
I'm about to remove the wrapper class

**Comment by ratacat** [comment]
@gcapozzo This doesn't work for some people, I'm not sure why. However, I did discover there is a configuration option already built in, it just wasn't documented anywhere. Made a pull request to document it, you can see it here. Very easy, works well for me.

https://github.com/run-llama/LlamaIndexTS/pull/1680
